{{- if .Values.customizationEnabled }}
{{- include "ibm-embed-helpers.requireObjectStorage" . }}
{{- include "ibm-embed-helpers.requirePostgres" . }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-watson-stt-embed.customization.fullname" . }}
  labels:
    {{- include "ibm-watson-stt-embed.customization.labels" . | nindent 4 }}
stringData:
  # object storage credentials
  objectStorageAccessKey: "{{ .Values.objectStorage.accessKey }}"
  objectStorageSecretKey: "{{ .Values.objectStorage.secretKey }}"
  # existing postgres user that must have privileges to create a database
  postgresUser: "{{ .Values.postgres.user }}"
  postgresPassword: "{{ .Values.postgres.password }}"

{{- end -}}
