# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CHRHDK
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-stt-runtime
    digest: sha256:4fa117cd400f5c4507e855d10aed6d56996b550e8d2039854c445869e1e8a92b
    tag: 1.8.0
  haproxy:
    repository: watson-stt-haproxy
    digest: sha256:0961fef7e1e09885026791dedcc5f9abf3375f3ccfb31f0393b155dd1ed6e322
    tag: 1.8.0
  catalog:
    repository: watson-stt-generic-models
    digest: sha256:cfcbe0aa5c3c97d1b590a27f3917720eae605f28201bdcebb7433f0cce818e3e
    tag: 1.8.0

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 1
      memory: 4Gi
      ephemeral-storage: 4Gi
    limits:
      cpu: 4
      memory: 4Gi
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no model is included in the /recognize request
defaultModel: en-US_Multimedia
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  arMSTelephony:
    catalogName: ar-MS_Telephony
    repository: watson-stt-ar-ms-telephony
    digest: sha256:d3e74cd4e24c9b62975e21926e2802466ad3ba421e127085a8b54006a51b287a
    tag: 1.8.0
    enabled: false
  csCZTelephony:
    catalogName: cs-CZ_Telephony
    repository: watson-stt-cs-cz-telephony
    digest: sha256:bb546e8ff74466dedd13a778aa09ab86e6a7cc6f460bbbafbee6408f6a265c3a
    tag: 1.8.0
    enabled: false
  deDEMultimedia:
    catalogName: de-DE_Multimedia
    repository: watson-stt-de-de-multimedia
    digest: sha256:52c56159ee250e4f3ba0baf77f097735a70c0a561e3f7d5e2a58c5e6e4aa6f60
    tag: 1.8.0
    enabled: false
  deDETelephony:
    catalogName: de-DE_Telephony
    repository: watson-stt-de-de-telephony
    digest: sha256:625890cfa2f1626362433ccb1ab5c3271ad9912550ddf458ce62df08005cda7e
    tag: 1.8.0
    enabled: false
  enUSMultimedia:
    catalogName: en-US_Multimedia
    repository: watson-stt-en-us-multimedia
    digest: sha256:eeffaee7f5caa65d2ba15102b36a3a13b01ffadc333cc4f2a5799471c9a79276
    tag: 1.8.0
    enabled: true
  enUSTelephony:
    catalogName: en-US_Telephony
    repository: watson-stt-en-us-telephony
    digest: sha256:64e2701f92d5a65336a342a9be5cc8aae3682ed37693bd457ccd82143e6c34a9
    tag: 1.8.0
    enabled: true
  enWWMedicalTelephony:
    catalogName: en-WW_Medical_Telephony
    repository: watson-stt-en-ww-medical-telephony
    digest: sha256:1930f41d1ffe0c6af6dcb159b9876966dbbba78f42a6e28328a1edede94d973d
    tag: 1.8.0
    enabled: false
  esESMultimedia:
    catalogName: es-ES_Multimedia
    repository: watson-stt-es-es-multimedia
    digest: sha256:85e5d1225005d3b38bed19dba687e1799c126d239255b746e90b90bac88a22bd
    tag: 1.8.0
    enabled: false
  esESTelephony:
    catalogName: es-ES_Telephony
    repository: watson-stt-es-es-telephony
    digest: sha256:e75ec0d6289ba2d4262641ba9697cfb1590ca649e028fb6526802acfcd626d6c
    tag: 1.8.0
    enabled: false
  esLATelephony:
    catalogName: es-LA_Telephony
    repository: watson-stt-es-la-telephony
    digest: sha256:7c85752aae8ac11ba0da222cbd08932190a563beb91a1878ea8bcf6f9b6fc0d1
    tag: 1.8.0
    enabled: false
  frCAMultimedia:
    catalogName: fr-CA_Multimedia
    repository: watson-stt-fr-ca-multimedia
    digest: sha256:eebe123dd2035a16d64e4fdd85a85503bc0e597f145637b8a33503254d1dd02b
    tag: 1.8.0
    enabled: false
  frCATelephony:
    catalogName: fr-CA_Telephony
    repository: watson-stt-fr-ca-telephony
    digest: sha256:2ec10cc52f2db006475a69ef85dae82a4dcbf472f87e5e548f911d02ea927a31
    tag: 1.8.0
    enabled: false
  frFRMultimedia:
    catalogName: fr-FR_Multimedia
    repository: watson-stt-fr-fr-multimedia
    digest: sha256:b2068bb7b8cab4061e36f0f49a681cad69ab2a452b2b13b5ceefd5e7f5bccd84
    tag: 1.8.0
    enabled: false
  frFRTelephony:
    catalogName: fr-FR_Telephony
    repository: watson-stt-fr-fr-telephony
    digest: sha256:6cc3aa72f0edf799905dace0d6f773a02b313b147dcea4b04320a301c8ca0159
    tag: 1.8.0
    enabled: false
  hiINTelephony:
    catalogName: hi-IN_Telephony
    repository: watson-stt-hi-in-telephony
    digest: sha256:054ad36b03f42c08de06e17b59612916f43771647400fc45641f48f0f81b76d7
    tag: 1.8.0
    enabled: false
  itITMultimedia:
    catalogName: it-IT_Multimedia
    repository: watson-stt-it-it-multimedia
    digest: sha256:48c23fdfd6962df2c10d27b593a2bf028741bcab41f752d473a6ecad8181f7c9
    tag: 1.8.0
    enabled: false
  itITTelephony:
    catalogName: it-IT_Telephony
    repository: watson-stt-it-it-telephony
    digest: sha256:3e0fa1dd74d4e20ecd26de8a1f0de7a42db7e6791b8fd83e7638a6276d765355
    tag: 1.8.0
    enabled: false
  jaJPMultimedia:
    catalogName: ja-JP_Multimedia
    repository: watson-stt-ja-jp-multimedia
    digest: sha256:76fd56743bf57aea322c1d30a3316e5652e2821383f9697a0b7421b119a6a866
    tag: 1.8.0
    enabled: false
  jaJPTelephony:
    catalogName: ja-JP_Telephony
    repository: watson-stt-ja-jp-telephony
    digest: sha256:221d3035ac85a381e580ce70b2508c3bf5954dce0326286df39092f4b1e7c0b1
    tag: 1.8.0
    enabled: false
  koKRMultimedia:
    catalogName: ko-KR_Multimedia
    repository: watson-stt-ko-kr-multimedia
    digest: sha256:4a13e96a86124859d68f3e76001fadf660c07c6d74ac40fc35638c9f93f0e816
    tag: 1.8.0
    enabled: false
  koKRTelephony:
    catalogName: ko-KR_Telephony
    repository: watson-stt-ko-kr-telephony
    digest: sha256:f9cfdefe11bc6e83a75664fcb80f797d92a26593a37352eb830d97d0f57cbfbb
    tag: 1.8.0
    enabled: false
  nlBETelephony:
    catalogName: nl-BE_Telephony
    repository: watson-stt-nl-be-telephony
    digest: sha256:9b5d0a69627c8b70828fce645c40c91e577dafea5a4b4faf03da2e8e05dff75b
    tag: 1.8.0
    enabled: false
  nlNLMultimedia:
    catalogName: nl-NL_Multimedia
    repository: watson-stt-nl-nl-multimedia
    digest: sha256:3cbcbef20d0bc406ebe713ac036968ab84a035bfa3282fe318bf5659a06bc3a5
    tag: 1.8.0
    enabled: false
  nlNLTelephony:
    catalogName: nl-NL_Telephony
    repository: watson-stt-nl-nl-telephony
    digest: sha256:e52efe955ef874fe1605108677ca682b23cb5d36dfbf26c9c2f3b2d54874e444
    tag: 1.8.0
    enabled: false
  ptBRMultimedia:
    catalogName: pt-BR_Multimedia
    repository: watson-stt-pt-br-multimedia
    digest: sha256:732e5186973fba92d07d62894e237d19ed97af1204d8232e69641dde70c93bb8
    tag: 1.8.0
    enabled: false
  ptBRTelephony:
    catalogName: pt-BR_Telephony
    repository: watson-stt-pt-br-telephony
    digest: sha256:e701b7381ec2e6fa18d6e87b0a6d49adebe84487112f442c02419e5aa9facc53
    tag: 1.8.0
    enabled: false
  svSETelephony:
    catalogName: sv-SE_Telephony
    repository: watson-stt-sv-se-telephony
    digest: sha256:38df6d4eddb0903cc895bddc9390c719ebd7f7bb20eb1dd7ad94c1988d0ffe10
    tag: 1.8.0
    enabled: false
  zhCNTelephony:
    catalogName: zh-CN_Telephony
    repository: watson-stt-zh-cn-telephony
    digest: sha256:833578b249bc54a155c2c1df7a215c91da54e78629b7e3585c690be29aff824a
    tag: 1.8.0
    enabled: false
