# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CHRHDK
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-stt-runtime
    digest: sha256:b395b004e43d3da4eab0c3c6669811d784d49f4d561f1e5f5f3ea850397ae5ec
    tag: 1.7.0
  haproxy:
    repository: watson-stt-haproxy
    digest: sha256:bf5f6e5e17936765f9f70051d997badb5011d37281173171038d7cda8c117711
    tag: 1.7.0
  catalog:
    repository: watson-stt-generic-models
    digest: sha256:beebccfdf5f7fdb79d1d95e9c5524ab4fb2d3330ad5a7e1018c9c89432b46c90
    tag: 1.7.0

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 1
      memory: 4Gi
      ephemeral-storage: 4Gi
    limits:
      cpu: 4
      memory: 4Gi
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no model is included in the /recognize request
defaultModel: en-US_Multimedia
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  arMSTelephony:
    catalogName: ar-MS_Telephony
    repository: watson-stt-ar-ms-telephony
    digest: sha256:8ad06448714a54832160c5f36d55a5a01c71fc7574b03f927e723aaae0327387
    tag: 1.7.0
    enabled: false
  csCZTelephony:
    catalogName: cs-CZ_Telephony
    repository: watson-stt-cs-cz-telephony
    digest: sha256:017ca5b2b6fafa4a03cc62b5d374040200e3a676e212dd91d338e8cf5b1d152e
    tag: 1.7.0
    enabled: false
  deDEMultimedia:
    catalogName: de-DE_Multimedia
    repository: watson-stt-de-de-multimedia
    digest: sha256:efc6b40247506d7cf2a80602d77a30c173ef46f7455057e39b141ce90ea390c5
    tag: 1.7.0
    enabled: false
  deDETelephony:
    catalogName: de-DE_Telephony
    repository: watson-stt-de-de-telephony
    digest: sha256:9ea7a8dd3f5e58165630dae2ff4d35f8eb0eeb99f6f6a54cf45b3fe64f0abbb7
    tag: 1.7.0
    enabled: false
  enINTelephony:
    catalogName: en-IN_Telephony
    repository: watson-stt-en-in-telephony
    digest: sha256:7d9fd9f01eb6c8253ac242f3930d75f27823f3cbc069a88adbc0848c3aacf974
    tag: 1.7.0
    enabled: false
  enUSMultimedia:
    catalogName: en-US_Multimedia
    repository: watson-stt-en-us-multimedia
    digest: sha256:e167e17b76b4bd3cb62bbd841822d79e3d3711605b13d79fb87b86a348c59bc6
    tag: 1.7.0
    enabled: true
  enUSTelephony:
    catalogName: en-US_Telephony
    repository: watson-stt-en-us-telephony
    digest: sha256:50a862bfe98a6da9c262cac64a28002b964db5e5efba93a9a90e349532dd4205
    tag: 1.7.0
    enabled: true
  enWWMedicalTelephony:
    catalogName: en-WW_Medical_Telephony
    repository: watson-stt-en-ww-medical-telephony
    digest: sha256:69fa5f27f5bbff14e6ec3cf38d898e9bec26d2024c43a7b30ff159435999e8dd
    tag: 1.7.0
    enabled: false
  esESMultimedia:
    catalogName: es-ES_Multimedia
    repository: watson-stt-es-es-multimedia
    digest: sha256:eaa4aedbb4a509b83ed5ecf1396bcc7415f0a30f3b9cb64eed858e636032ce01
    tag: 1.7.0
    enabled: false
  esESTelephony:
    catalogName: es-ES_Telephony
    repository: watson-stt-es-es-telephony
    digest: sha256:4464d39201dbe3969304bb7bd67908936db611783f59718989bc426031be97d6
    tag: 1.7.0
    enabled: false
  esLATelephony:
    catalogName: es-LA_Telephony
    repository: watson-stt-es-la-telephony
    digest: sha256:e6afcdd0250816a4f0c14ee40b6860f5216797a9a52c29ddc638bb45be25ba5b
    tag: 1.7.0
    enabled: false
  frCAMultimedia:
    catalogName: fr-CA_Multimedia
    repository: watson-stt-fr-ca-multimedia
    digest: sha256:0625b13b7d01f65af7fd828bf1878838808b8c9faab87b2b0292697e5b7837c8
    tag: 1.7.0
    enabled: false
  frCATelephony:
    catalogName: fr-CA_Telephony
    repository: watson-stt-fr-ca-telephony
    digest: sha256:fc55ff429ba0036725c8757a7c000d07ff080d1c6ac5d399cf2b8d7356ac6e53
    tag: 1.7.0
    enabled: false
  frFRMultimedia:
    catalogName: fr-FR_Multimedia
    repository: watson-stt-fr-fr-multimedia
    digest: sha256:d7d384f85b8a6960fe8c53c2c02fbf33b277ca314269bbdb586ef1d8206f958c
    tag: 1.7.0
    enabled: false
  frFRTelephony:
    catalogName: fr-FR_Telephony
    repository: watson-stt-fr-fr-telephony
    digest: sha256:dfb53923931c0fe444ded9d270aebb0fca9c4fd03754808f12cb025243fdac14
    tag: 1.7.0
    enabled: false
  hiINTelephony:
    catalogName: hi-IN_Telephony
    repository: watson-stt-hi-in-telephony
    digest: sha256:c6ab94a50d9f75bdd3f9136b2d27085abf053876bb68b743916ff44b6b68347b
    tag: 1.7.0
    enabled: false
  itITMultimedia:
    catalogName: it-IT_Multimedia
    repository: watson-stt-it-it-multimedia
    digest: sha256:58c823924afb682b52e667cf3c9981bd0e0965e0cfdab99e030a5ad2935901c9
    tag: 1.7.0
    enabled: false
  itITTelephony:
    catalogName: it-IT_Telephony
    repository: watson-stt-it-it-telephony
    digest: sha256:366a00a7deef822ddbb114e231bbb0982864e552f3730caf621e1359ad8be3a9
    tag: 1.7.0
    enabled: false
  jaJPMultimedia:
    catalogName: ja-JP_Multimedia
    repository: watson-stt-ja-jp-multimedia
    digest: sha256:1f4be8c18668542de0b0fe642f27d0a562b8a9e7c8321c6c866b336352bc652a
    tag: 1.7.0
    enabled: false
  jaJPTelephony:
    catalogName: ja-JP_Telephony
    repository: watson-stt-ja-jp-telephony
    digest: sha256:016468da7ee2b2954018302176aca346fa5aa66476c47ce075375dcca8ac8f62
    tag: 1.7.0
    enabled: false
  koKRMultimedia:
    catalogName: ko-KR_Multimedia
    repository: watson-stt-ko-kr-multimedia
    digest: sha256:463bb8dca901a25ee8147b01aad15050a65be08eaddd4859ef38bfec4fe1c4b9
    tag: 1.7.0
    enabled: false
  koKRTelephony:
    catalogName: ko-KR_Telephony
    repository: watson-stt-ko-kr-telephony
    digest: sha256:085cf455d3a29bdc1349899639c266738f0b648f2408878bc170a80400e3ef83
    tag: 1.7.0
    enabled: false
  nlBETelephony:
    catalogName: nl-BE_Telephony
    repository: watson-stt-nl-be-telephony
    digest: sha256:5948f1bed60411bb44330c7d7011442b4bc604917c7b565a542ddcaf7b751719
    tag: 1.7.0
    enabled: false
  nlNLMultimedia:
    catalogName: nl-NL_Multimedia
    repository: watson-stt-nl-nl-multimedia
    digest: sha256:b650bf789b165c22cdd7aaa09d608f252b7a720c06e8ee9f49e1bae088523dae
    tag: 1.7.0
    enabled: false
  nlNLTelephony:
    catalogName: nl-NL_Telephony
    repository: watson-stt-nl-nl-telephony
    digest: sha256:238c48e55702905b30829b618abff63c72f6560a996b5525a93219e28df92bfb
    tag: 1.7.0
    enabled: false
  ptBRMultimedia:
    catalogName: pt-BR_Multimedia
    repository: watson-stt-pt-br-multimedia
    digest: sha256:bfe6ec3085963cd48513b6fba842644afb5afa5d0c9f3fa1e47e9fd27ab3bdfd
    tag: 1.7.0
    enabled: false
  ptBRTelephony:
    catalogName: pt-BR_Telephony
    repository: watson-stt-pt-br-telephony
    digest: sha256:0f3ff5b27176f874f8ad2fefb8a9b50755c2bdaba43bc6789db1125ab3bfbb77
    tag: 1.7.0
    enabled: false
  svSETelephony:
    catalogName: sv-SE_Telephony
    repository: watson-stt-sv-se-telephony
    digest: sha256:45c83cdaddd087e383a9b93c7a76e9e55e80aa91818ebc6414ed571610b26124
    tag: 1.7.0
    enabled: false
  zhCNTelephony:
    catalogName: zh-CN_Telephony
    repository: watson-stt-zh-cn-telephony
    digest: sha256:1897cf5d71040b7ba33ab19a9dcae3ac5b50c8d26ce7c1cd1c9b4b8fa0f6e702
    tag: 1.7.0
    enabled: false
