# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CHRHDK
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-stt-runtime
    digest: sha256:c5ad7754895e1b0b9c48714562049cc08f042fb75c670ae4f7392cfd6fe7676b
    tag: 1.10.0
  haproxy:
    repository: watson-stt-haproxy
    digest: sha256:5bc6e090741b0a58fa14d854ca157856fc578de27f9c938e1295e2329b3662ab
    tag: 1.10.0
  catalog:
    repository: watson-stt-generic-models
    digest: sha256:ce3618d77e81d754898c81d29bbfbf8e50bb14cf68da6ee272cc7679a8a611f2
    tag: 1.10.0

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 2
      memory: 5Gi
      ephemeral-storage: 5Gi
    limits:
      cpu: 4
      memory: 50Gi
      ephemeral-storage: 50Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no model is included in the /recognize request
defaultModel: en-US_Multimedia
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  arMSTelephony:
    catalogName: ar-MS_Telephony
    repository: watson-stt-ar-ms-telephony
    digest: sha256:1b8e0e11468cdd57c35f38ce485231f46086b8997deda815b0620b645ffd80d1
    tag: 1.10.0
    enabled: false
  csCZTelephony:
    catalogName: cs-CZ_Telephony
    repository: watson-stt-cs-cz-telephony
    digest: sha256:c39b31c419552d662ef815a111359638a230e050a03141e89dc00ed3e6838d4e
    tag: 1.10.0
    enabled: false
  deDEMultimedia:
    catalogName: de-DE_Multimedia
    repository: watson-stt-de-de-multimedia
    digest: sha256:5b3b2c0ffe3d85df132bdb6f4a2840fcc11d5c2b0063f7c6fb914ed1a1d62c99
    tag: 1.10.0
    enabled: false
  deDETelephony:
    catalogName: de-DE_Telephony
    repository: watson-stt-de-de-telephony
    digest: sha256:befdb3c2dffe0d7bc282e595c59a25ba75e50fb143d6b0098581cb328b6d2e7f
    tag: 1.10.0
    enabled: false
  enUSMultimedia:
    catalogName: en-US_Multimedia
    repository: watson-stt-en-us-multimedia
    digest: sha256:fb9ca649330eef27e69e893b057cbd348b7e762f232c8a76b8b0845115361ca1
    tag: 1.10.0
    enabled: true
  enUSTelephony:
    catalogName: en-US_Telephony
    repository: watson-stt-en-us-telephony
    digest: sha256:7f5b1837575ec2aecc1489399488c652c4b35d95283401b80f1a9246cf7006bd
    tag: 1.10.0
    enabled: true  
  enWWMedicalTelephony:
    catalogName: en-WW_Medical_Telephony
    repository: watson-stt-en-ww-medical-telephony
    digest: sha256:2fd992f59e2ac0906e32f2e5d3f1ddb65d9a60e66c3334a2d356d4e5cd22d38a
    tag: 1.10.0
    enabled: false
  esESMultimedia:
    catalogName: es-ES_Multimedia
    repository: watson-stt-es-es-multimedia
    digest: sha256:46fbfe77b00bccc0c1352704cda2e696cb4fcacdff32baf126bf04b0c937a5e0
    tag: 1.10.0
    enabled: false
  esESTelephony:
    catalogName: es-ES_Telephony
    repository: watson-stt-es-es-telephony
    digest: sha256:d55dd0bacb09b1dc041d5b6d07f04e0cb0853acb07af6a00f3c0f85c3e24d5cd
    tag: 1.10.0
    enabled: false
  esLATelephony:
    catalogName: es-LA_Telephony
    repository: watson-stt-es-la-telephony
    digest: sha256:79039a566172aae344986592c011df7037e0e3723c9e39e476ed4ca50b98a585
    tag: 1.10.0
    enabled: false
  frCAMultimedia:
    catalogName: fr-CA_Multimedia
    repository: watson-stt-fr-ca-multimedia
    digest: sha256:81c52dcbc2562d5e59d84c39c6ea8cdc66dc5c1b64b79836d720e95e48bddf79
    tag: 1.10.0
    enabled: false
  frCATelephony:
    catalogName: fr-CA_Telephony
    repository: watson-stt-fr-ca-telephony
    digest: sha256:ad23c938804e1dda3454b5f2bb7ba99723da0b639b8e633a827478b0ec781116
    tag: 1.10.0
    enabled: false
  frFRMultimedia:
    catalogName: fr-FR_Multimedia
    repository: watson-stt-fr-fr-multimedia
    digest: sha256:6647e7af608322a5c0c4439d65c25a18d6766a4df80d8bf14fa5625cf9104d07
    tag: 1.10.0
    enabled: false
  frFRTelephony:
    catalogName: fr-FR_Telephony
    repository: watson-stt-fr-fr-telephony
    digest: sha256:3bbdc411b7048f3f5778d080158c00eae1306f8a38e12b30ea04e635929d12aa
    tag: 1.10.0
    enabled: false  
  hiINTelephony:
    catalogName: hi-IN_Telephony
    repository: watson-stt-hi-in-telephony
    digest: sha256:56981a1951aeffd2118f9e983c04231677ac6ab0d2ff861b5d89b6b3168da514
    tag: 1.10.0
    enabled: false
  itITMultimedia:
    catalogName: it-IT_Multimedia
    repository: watson-stt-it-it-multimedia
    digest: sha256:65ae5a41974453f156bd27ce610db6a774ef6ffdedd65fb57a7dc655d38d0845
    tag: 1.10.0
    enabled: false
  itITTelephony:
    catalogName: it-IT_Telephony
    repository: watson-stt-it-it-telephony
    digest: sha256:60668fb76bad858f782b087c2998a41940cd249fbcf180a5218875d55402e5f1
    tag: 1.10.0
    enabled: false
  jaJPMultimedia:
    catalogName: ja-JP_Multimedia
    repository: watson-stt-ja-jp-multimedia
    digest: sha256:fecb34446e51efc49ca2580103c4e1ffb82382dd19a5b7b174ddd8c990c560fc
    tag: 1.10.0
    enabled: false
  jaJPTelephony:
    catalogName: ja-JP_Telephony
    repository: watson-stt-ja-jp-telephony
    digest: sha256:b24a4fa6abd1b233ba5d6f98cd3e1c9fd3b5504675a224f6a9f68b2f476b29b1
    tag: 1.10.0
    enabled: false  
  koKRMultimedia:
    catalogName: ko-KR_Multimedia
    repository: watson-stt-ko-kr-multimedia
    digest: sha256:d098fe04a7431dd99c9ded928364ac4d6f03ac58405143dae0acf71b2458f972
    tag: 1.10.0
    enabled: false
  koKRTelephony:
    catalogName: ko-KR_Telephony
    repository: watson-stt-ko-kr-telephony
    digest: sha256:4086859db507d5896cc4c6654020f4d08ba75218b5611026aae243744eb273b4
    tag: 1.10.0
    enabled: false
  nlBETelephony:
    catalogName: nl-BE_Telephony
    repository: watson-stt-nl-be-telephony
    digest: sha256:26afd82b62a01fbb087ef9222647b9151fc9fffac00ce66af83a78018d497caf
    tag: 1.10.0
    enabled: false
  nlNLMultimedia:
    catalogName: nl-NL_Multimedia
    repository: watson-stt-nl-nl-multimedia
    digest: sha256:b85127ad789ef60bfa87ae3638f8ec8237350d441a3d545ab9f38ce5c80be26d
    tag: 1.10.0
    enabled: false
  nlNLTelephony:
    catalogName: nl-NL_Telephony
    repository: watson-stt-nl-nl-telephony
    digest: sha256:4a27e26bbd1d6496dd85a8c81608a83ff923decc4c35d727a6e3e2e3900e990c
    tag: 1.10.0
    enabled: false
  ptBRMultimedia:
    catalogName: pt-BR_Multimedia
    repository: watson-stt-pt-br-multimedia
    digest: sha256:129c993c42d3b90280cfb2e74ff0e2179de9d02522d761e8a6d0c92fe3ab00e2
    tag: 1.10.0
    enabled: false
  ptBRTelephony:
    catalogName: pt-BR_Telephony
    repository: watson-stt-pt-br-telephony
    digest: sha256:0050755123f3b67cf67432ede0fbb13ccdecceeafc16c5ca9ce5d0dac9449b44
    tag: 1.10.0
    enabled: false
  svSETelephony:
    catalogName: sv-SE_Telephony
    repository: watson-stt-sv-se-telephony
    digest: sha256:8da1b75dbbfaab08cfcfac3aa59ae23c9ce3b3fa4f08d23df57922e3d44e2dc2
    tag: 1.10.0
    enabled: false
  zhCNTelephony:
    catalogName: zh-CN_Telephony
    repository: watson-stt-zh-cn-telephony
    digest: sha256:0311871815f267bead0de031ce299afb18734125a91f062f8769da287c7b38b3
    tag: 1.10.0
    enabled: false
