# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CHRHDK
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-stt-runtime
    digest: sha256:7d1dc56ccaf38b73d57e25430515b869c8435fa81fa0db28576f5ccb465a64b0
    tag: 1.12.0
  haproxy:
    repository: watson-stt-haproxy
    digest: sha256:99cd91f0633e3e583eebb53126f39d4fddfec33efe6a808d5c207d34fcd76cd0
    tag: 1.12.0
  catalog:
    repository: watson-stt-generic-models
    digest: sha256:8f2c3f7bf227d5b0bb25f33072a05c2c7dc56d564b03af8dca4b8df06ab2197b
    tag: 1.12.0

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 2
      memory: 5Gi
      ephemeral-storage: 5Gi
    limits:
      cpu: 4
      memory: 50Gi
      ephemeral-storage: 50Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no model is included in the /recognize request
defaultModel: en-US_Multimedia
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  arMSTelephony:
    catalogName: ar-MS_Telephony
    repository: watson-stt-ar-ms-telephony
    digest: sha256:ade0e30f51a014bf297220b76b980b44d488aa9aa0924ff5c3fae1ae3051f49e
    tag: 1.12.0
    enabled: false
  csCZTelephony:
    catalogName: cs-CZ_Telephony
    repository: watson-stt-cs-cz-telephony
    digest: sha256:62380e7934fa4f2f7efdb572747261c461412050871a28ad164b39d37ea155e6
    tag: 1.12.0
    enabled: false
  deDEMultimedia:
    catalogName: de-DE_Multimedia
    repository: watson-stt-de-de-multimedia
    digest: sha256:6c74e3de61daaccd480b98b0b243ea5b45a989ea3406544526e87f863df6c3ff
    tag: 1.12.0
    enabled: false
  deDETelephony:
    catalogName: de-DE_Telephony
    repository: watson-stt-de-de-telephony
    digest: sha256:28b75da6e353c13e08cfdefd83ad68e2d89baa158d5ed6f1fc57b51c2b94eb2d
    tag: 1.12.0
    enabled: false
  enUSMultimedia:
    catalogName: en-US_Multimedia
    repository: watson-stt-en-us-multimedia
    digest: sha256:58631da4d9d2c08a1f19b10a0d3d8e37f226953cb6f19e33507e2b1dc8573b8e
    tag: 1.12.0
    enabled: true
  enUSTelephony:
    catalogName: en-US_Telephony
    repository: watson-stt-en-us-telephony
    digest: sha256:0c63d233bd8d031234c574e71c4156f1ab04143cb8cb76215201306fd5155d49
    tag: 1.12.0
    enabled: true
  enUSTelephonyLSM:
    catalogName: en-US_Telephony_LSM
    repository: watson-stt-en-us-telephony-lsm
    digest: sha256:b6f05031337258362b69963d7592f40f939e8e181b49f124cca9c0d3e5a18a8e
    tag: 1.12.0
    enabled: false
  enWWMedicalTelephony:
    catalogName: en-WW_Medical_Telephony
    repository: watson-stt-en-ww-medical-telephony
    digest: sha256:41a159e4d57da6c3037fc45cc686a40d9252ad82376a0629fbe62c360b64b40b
    tag: 1.12.0
    enabled: false
  esESMultimedia:
    catalogName: es-ES_Multimedia
    repository: watson-stt-es-es-multimedia
    digest: sha256:feb3e8a333aeb166568408c9bb2026b5aed2cbe9e5ae7bd6eadb498eb6f91fab
    tag: 1.12.0
    enabled: false
  esESTelephony:
    catalogName: es-ES_Telephony
    repository: watson-stt-es-es-telephony
    digest: sha256:d2ac8334f6a9aa7e8c8ac8d35588bd5b747eee32705f15f3ae941cd9bbed94ef
    tag: 1.12.0
    enabled: false
  esESTelephonyLSM:
    catalogName: es-ES_Telephony_LSM
    repository: watson-stt-es-es-telephony-lsm
    digest: sha256:dfdbf94f506e48306fb83384549a2ab14e4ba58694ec25084370c841fa3a2041
    tag: 1.12.0
    enabled: false
  esLATelephony:
    catalogName: es-LA_Telephony
    repository: watson-stt-es-la-telephony
    digest: sha256:15a3177bed46ac37463343acf389939c1c33c2ef4839b618d601ed4b6543cb27
    tag: 1.12.0
    enabled: false
  frCAMultimedia:
    catalogName: fr-CA_Multimedia
    repository: watson-stt-fr-ca-multimedia
    digest: sha256:5072f48d770418acfe76b22909fff25412ec91f07fea39ddd2548e7c12aa897e
    tag: 1.12.0
    enabled: false
  frCATelephony:
    catalogName: fr-CA_Telephony
    repository: watson-stt-fr-ca-telephony
    digest: sha256:d2f92785840cf895890f0d8e46c14366fd377809acf6fa59b56bf279b03fe03a
    tag: 1.12.0
    enabled: false
  frFRMultimedia:
    catalogName: fr-FR_Multimedia
    repository: watson-stt-fr-fr-multimedia
    digest: sha256:8da20b0fe2bc6017872458ca50dc8f00b5a6b8ec6b78c73737f81f0b85eeb049
    tag: 1.12.0
    enabled: false
  frFRTelephony:
    catalogName: fr-FR_Telephony
    repository: watson-stt-fr-fr-telephony
    digest: sha256:226423275234d624137703389e7b7f792851fb841d91a08d6c9d7adcb0b1f66b
    tag: 1.12.0
    enabled: false
  frFRTelephonyLSM:
    catalogName: fr-FR_Telephony_LSM
    repository: watson-stt-fr-fr-telephony-lsm
    digest: sha256:d690f38241d4c8b5529cd1258bff4c15e591aba21ae837d7e203aa143456de58
    tag: 1.12.0
    enabled: false
  hiINTelephony:
    catalogName: hi-IN_Telephony
    repository: watson-stt-hi-in-telephony
    digest: sha256:089ba52c3ccd2effbfa3fa7be9ebc772d47116c819856d53913d4d99e1914550
    tag: 1.12.0
    enabled: false
  itITMultimedia:
    catalogName: it-IT_Multimedia
    repository: watson-stt-it-it-multimedia
    digest: sha256:d11e0e431c40eb065314c1377d701484beb84ec55b236429b6d317daa8e39398
    tag: 1.12.0
    enabled: false
  itITTelephony:
    catalogName: it-IT_Telephony
    repository: watson-stt-it-it-telephony
    digest: sha256:db52cfcfd63df787d3f9ad2dc4ecc93ff0d236978a69e13273b4fa4d0dbf42e3
    tag: 1.12.0
    enabled: false
  jaJPMultimedia:
    catalogName: ja-JP_Multimedia
    repository: watson-stt-ja-jp-multimedia
    digest: sha256:2af1613d9bfda71edb3047415aeebc5d82dc58e3d8c21e13e752817e8011a479
    tag: 1.12.0
    enabled: false
  jaJPTelephony:
    catalogName: ja-JP_Telephony
    repository: watson-stt-ja-jp-telephony
    digest: sha256:955dac5f98bd7bd57a0e85a873ea5319ee92a0e09517e1afa109ec30d1b13982
    tag: 1.12.0
    enabled: false
  jaJPTelephonyLSM:
    catalogName: ja-JP_Telephony_LSM
    repository: watson-stt-ja-jp-telephony-lsm
    digest: sha256:1a45a76c7c4a29d205c142913a33aa49465148931a1caa10a9bb8bfa6afdd5a2
    tag: 1.12.0
    enabled: false
  koKRMultimedia:
    catalogName: ko-KR_Multimedia
    repository: watson-stt-ko-kr-multimedia
    digest: sha256:4e5feccf941af89652e7bd337df621d430b7a8707356bf6946f130d79418e1a0
    tag: 1.12.0
    enabled: false
  koKRTelephony:
    catalogName: ko-KR_Telephony
    repository: watson-stt-ko-kr-telephony
    digest: sha256:fc1be1a861b18f1221f2f5be63169535cb8c6db4d757e50a45813471fc0fed55
    tag: 1.12.0
    enabled: false
  nlBETelephony:
    catalogName: nl-BE_Telephony
    repository: watson-stt-nl-be-telephony
    digest: sha256:d0a3f6a523e55e8681c1a3ec09031c1a6767711b6c22ecc3ff14105595008572
    tag: 1.12.0
    enabled: false
  nlNLMultimedia:
    catalogName: nl-NL_Multimedia
    repository: watson-stt-nl-nl-multimedia
    digest: sha256:f02623c2ade0f950c52254c1d1bc5bc47a21d3e18587a548d73d01175d9687d1
    tag: 1.12.0
    enabled: false
  nlNLTelephony:
    catalogName: nl-NL_Telephony
    repository: watson-stt-nl-nl-telephony
    digest: sha256:ce586c44c3d1eb092f0fb06bb7de417bd76eb761c14b4ce5bb4abc78003d4543
    tag: 1.12.0
    enabled: false
  ptBRMultimedia:
    catalogName: pt-BR_Multimedia
    repository: watson-stt-pt-br-multimedia
    digest: sha256:10b5e861f37ce1098f89bb8b64c91b3b9fc11d7476591d6f7bca4d4bd593e272
    tag: 1.12.0
    enabled: false
  ptBRTelephony:
    catalogName: pt-BR_Telephony
    repository: watson-stt-pt-br-telephony
    digest: sha256:7f94caf798cd9e73dab7f49475e7a247d0c4e0335aaa53dc5f59b94410040178
    tag: 1.12.0
    enabled: false
  ptBRTelephonyLSM:
    catalogName: pt-BR_Telephony_LSM
    repository: watson-stt-pt-br-telephony-lsm
    digest: sha256:3401f3d2c2a0572f77d1a1f28e5519deb23a98e098e52611143d65e3f026f483
    tag: 1.12.0
    enabled: false
  svSETelephony:
    catalogName: sv-SE_Telephony
    repository: watson-stt-sv-se-telephony
    digest: sha256:f4ffc5aff6cd8f9568cb0438d61c772af942a4142cab499344449c79f6287a29
    tag: 1.12.0
    enabled: false
  zhCNTelephony:
    catalogName: zh-CN_Telephony
    repository: watson-stt-zh-cn-telephony
    digest: sha256:1939709cb8268b01f7221ceb6394123ca509e69837d560dc9ab0f14fd6bd3d96
    tag: 1.12.0
    enabled: false
