{{- include "ibm-embed-helpers.requireObjectStorage" . }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-watson-tts-embed.runtime.fullname" . }}
  labels:
    {{- include "ibm-watson-tts-embed.runtime.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
stringData:
  accesskey: {{ .Values.objectStorage.accessKey }}
  secretkey: {{ .Values.objectStorage.secretKey }}
