# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CHRHDK
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# General Configuration

customizationEnabled: true

# readOnlyRootFilesystem controls the setting in the container security context
#
# NB: With customizationEnabled, the runtime container must have a read-write
# filesystem to support training of customizations. The value here is not
# respected for the runtime container in that case.
readOnlyRootFilesystem: true

serviceType: ClusterIP
# uploadModelConcurrency controls the number of models uploaded per upload job
# Jobs are run sequentially, so this affects the total duration.
uploadModelConcurrency: 5

# Service Dependencies

# objectStorage has configuration for an s3 compatible object storage for models storage
objectStorage:
  endpoint: ""
  region: ""
  bucket: speech-embed
  accessKey: ""
  secretKey: ""

# postgres has configuration for a PostgreSQL instance that will store data and
# metadata for customizations
postgres:
  # host is the hostname of server hosting the Postgres instance
  host: ""
  # port to connect to on the hostname
  port: 5432
  # loginDatabase is the database used to establish the connection before creating the customizations database
  loginDatabase: "postgres"
  # user is the existing user that will own the customizations database and be used at runtime
  user: ""
  # password is the password for user
  password: ""
  # databaseName is the database that will be created/used to hold data about customizations
  databaseName: "stt-customizations"

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      memory: 4Gi
      cpu: 1
      ephemeral-storage: 4Gi
    limits:
      memory: 4Gi
      cpu: 4
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      memory: 1Gi
      cpu: 0.2
      ephemeral-storage: 64Mi
    limits:
      memory: 1Gi
      cpu: 1
      ephemeral-storage: 64Mi
  customization:
    requests:
      memory: 2Gi
      cpu: 0.5
      ephemeral-storage: 2Gi
    limits:
      memory: 2Gi
      cpu: 1
      ephemeral-storage: 2Gi

# images configures which container images are used
# To pull by tag, set digest to the empty string
images:
  utils:
    repository: watson-stt-utils
    digest: sha256:c9e7ce00e141e4bbda03a2a0e2fa09a9c592ec245b78727a1257d6427dd16e22
    tag: 1.6.0
  runtime:
    repository: watson-stt-runtime
    digest: sha256:e9c67d95ee4c4ce2b2a4d4ee30d5d33a65e106cf9022ac89f99b5711d06b4aec
    tag: 1.6.0
  haproxy:
    repository: watson-stt-haproxy
    digest: sha256:8e65ee8fbc21cb84ecd08f83f26ee352b6ca285ff5bdd8853031cd8ae0d06483
    tag: 1.6.0
  customization:
    repository: watson-stt-customization
    digest: sha256:c443aed277eb6ad8517d9e584bd58b4ef1cbaf8ed194f3ed7718f9b2146d4dc0
    tag: 1.6.0
  catalog:
    repository: watson-stt-generic-models
    digest: sha256:20ecffc883dc3ee54806bff2d56b3520762690deb0b1ca79bae097862497613c
    tag: 1.6.0


# defaultModel will be used if no model is included in the /recognize request
defaultModel: en-US_Multimedia
# modelVersion sets the path within model storage where the catalog will be uploaded
modelVersion: "1.6.0"
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  arMSTelephony:
    catalogName: ar-MS_Telephony
    repository: watson-stt-ar-ms-telephony
    digest: sha256:4790d2d86f6c4f28a8a3d5db69f203d4f11f841e56abd1b5a77ab9a4bfc1d5b1
    tag: 1.6.0
    enabled: false
  csCZTelephony:
    catalogName: cs-CZ_Telephony
    repository: watson-stt-cs-cz-telephony
    digest: sha256:63cc379fb207cc88d348074882de6f1f3a533cafe285c1686941fa9525ef1af5
    tag: 1.6.0
    enabled: false
  deDEMultimedia:
    catalogName: de-DE_Multimedia
    repository: watson-stt-de-de-multimedia
    digest: sha256:244ff6e70aab1b05311d554118643e4061fe83886c60cad3ecce8fbd545b6494
    tag: 1.6.0
    enabled: false
  deDETelephony:
    catalogName: de-DE_Telephony
    repository: watson-stt-de-de-telephony
    digest: sha256:f34b9af7f9b7e4fe2d708056cfa1d8af38556e956b84a22318779d19096852a0
    tag: 1.6.0
    enabled: false
  enINTelephony:
    catalogName: en-IN_Telephony
    repository: watson-stt-en-in-telephony
    digest: sha256:b63ced934880a02674a0c5b658287600e76f19552aabe2efbbe5eed831b309ae
    tag: 1.6.0
    enabled: false
  enUSMultimedia:
    catalogName: en-US_Multimedia
    repository: watson-stt-en-us-multimedia
    digest: sha256:fd193f5c3b179632ca906580f6f2a555c76b527aead6b12e0050972aeaabb7f3
    tag: 1.6.0
    enabled: true
  enUSTelephony:
    catalogName: en-US_Telephony
    repository: watson-stt-en-us-telephony
    digest: sha256:06f4d51664b354b96b695300918312b02ef4340406f271a0b265361ca51e7fa6
    tag: 1.6.0
    enabled: true
  enWWMedicalTelephony:
    catalogName: en-WW_Medical_Telephony
    repository: watson-stt-en-ww-medical-telephony
    digest: sha256:fb054b970e1ddf6a573a636a9ccbd2b3552c46ac8dd30174856b94d7a81ab8ef
    tag: 1.6.0
    enabled: false
  esESMultimedia:
    catalogName: es-ES_Multimedia
    repository: watson-stt-es-es-multimedia
    digest: sha256:b26c0006885203df1f0b19982803e17956567e263dfae1b0e36cbc89612875bc
    tag: 1.6.0
    enabled: false
  esESTelephony:
    catalogName: es-ES_Telephony
    repository: watson-stt-es-es-telephony
    digest: sha256:196d13ba536b69eb74f2d53229dcd30fd9dbb77382a756427b0a634aca30c68f
    tag: 1.6.0
    enabled: false
  esLATelephony:
    catalogName: es-LA_Telephony
    repository: watson-stt-es-la-telephony
    digest: sha256:70a8ca27658d1bce12d38ad1c446ffb7a62dc6308afbe3a7443a02533fd06372
    tag: 1.6.0
    enabled: false
  frCAMultimedia:
    catalogName: fr-CA_Multimedia
    repository: watson-stt-fr-ca-multimedia
    digest: sha256:77f132cd3bde169d4c5b868646cb7cf249577eceeb1f645e8ca9c023ad3344e2
    tag: 1.6.0
    enabled: false
  frCATelephony:
    catalogName: fr-CA_Telephony
    repository: watson-stt-fr-ca-telephony
    digest: sha256:f451165dbbae4d65dd0514e97a8d58e68092ef047d611c52e7513cf118e67d07
    tag: 1.6.0
    enabled: false
  frFRMultimedia:
    catalogName: fr-FR_Multimedia
    repository: watson-stt-fr-fr-multimedia
    digest: sha256:14ac31448bb22c9d641a4315274b63786c2ab13ee7976a29ded7d0aebb2dcecf
    tag: 1.6.0
    enabled: false
  frFRTelephony:
    catalogName: fr-FR_Telephony
    repository: watson-stt-fr-fr-telephony
    digest: sha256:7955a29bcd8102fa1fdbaf35209d579ae2d674922ebf15950b2aa6ede194d890
    tag: 1.6.0
    enabled: false
  hiINTelephony:
    catalogName: hi-IN_Telephony
    repository: watson-stt-hi-in-telephony
    digest: sha256:cacbdddb60904a697572bfffe9068e546f84d60b7a1f3948943cb7122f36344d
    tag: 1.6.0
    enabled: false
  itITMultimedia:
    catalogName: it-IT_Multimedia
    repository: watson-stt-it-it-multimedia
    digest: sha256:9f4358c2451c74ba6be5519d1f6b69ea24e7a5c44164621235607a059d709450
    tag: 1.6.0
    enabled: false
  itITTelephony:
    catalogName: it-IT_Telephony
    repository: watson-stt-it-it-telephony
    digest: sha256:ebec5f135b9d30605d14b8266c19ec8be5616527aea2644d0114ae4096ea2694
    tag: 1.6.0
    enabled: false
  jaJPMultimedia:
    catalogName: ja-JP_Multimedia
    repository: watson-stt-ja-jp-multimedia
    digest: sha256:0f122621cc9b1739731897d7cf8233bb7022bb7bfed59a0d9cce2040011aff4b
    tag: 1.6.0
    enabled: false
  jaJPTelephony:
    catalogName: ja-JP_Telephony
    repository: watson-stt-ja-jp-telephony
    digest: sha256:b2dc306de1bc63198fb80bf5951298d4428cbf57564d53aadc5f3fafa43c5f30
    tag: 1.6.0
    enabled: false
  koKRMultimedia:
    catalogName: ko-KR_Multimedia
    repository: watson-stt-ko-kr-multimedia
    digest: sha256:89489afe9831083761821a1df3e1f5ffa4db9eab36d47db38800ac8b44d1cdb3
    tag: 1.6.0
    enabled: false
  koKRTelephony:
    catalogName: ko-KR_Telephony
    repository: watson-stt-ko-kr-telephony
    digest: sha256:d3e9428b96435a100b38558bf166a8217ca860431502b8f0e2e9a19ea95f4e42
    tag: 1.6.0
    enabled: false
  nlBETelephony:
    catalogName: nl-BE_Telephony
    repository: watson-stt-nl-be-telephony
    digest: sha256:55d296c94a13ab327148056ad92153fd2552a5df7099bdbae8b1c578ba5bd2e0
    tag: 1.6.0
    enabled: false
  nlNLMultimedia:
    catalogName: nl-NL_Multimedia
    repository: watson-stt-nl-nl-multimedia
    digest: sha256:c8886f58d130707ca4c2f194eeb791c4637c60b0e184856c5a52348e422aff75
    tag: 1.6.0
    enabled: false
  nlNLTelephony:
    catalogName: nl-NL_Telephony
    repository: watson-stt-nl-nl-telephony
    digest: sha256:ddbb8b6cce19dfbcffab6b6bf049912aca2205bf04906dd4a9410f9a9aa81f7d
    tag: 1.6.0
    enabled: false
  ptBRMultimedia:
    catalogName: pt-BR_Multimedia
    repository: watson-stt-pt-br-multimedia
    digest: sha256:207103b70ab5140fd5ec7c9f5aafd464ce925187943cba5f7a5f61a8887c8ee9
    tag: 1.6.0
    enabled: false
  ptBRTelephony:
    catalogName: pt-BR_Telephony
    repository: watson-stt-pt-br-telephony
    digest: sha256:2a169bf919511d292c149563d3aa21988a3e8eb8a8776444fb64ef4523dc112a
    tag: 1.6.0
    enabled: false
  svSETelephony:
    catalogName: sv-SE_Telephony
    repository: watson-stt-sv-se-telephony
    digest: sha256:9f39a63caba3106071e40055be94ddd0172e82ec5fed91fc07ca52d29288db32
    tag: 1.6.0
    enabled: false
  zhCNTelephony:
    catalogName: zh-CN_Telephony
    repository: watson-stt-zh-cn-telephony
    digest: sha256:8f981def6142df02d22c3272c2d238c1842e1bb1ccde42b63c0ea163290d84c0
    tag: 1.6.0
    enabled: false