# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CJULPU
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# General Configuration

customizationEnabled: true

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP
# uploadModelConcurrency controls the number of models uploaded per upload job
# Jobs are run sequentially, so this affects the total duration.
uploadModelConcurrency: 5

# Service Dependencies

# objectStorage has configuration for an s3 compatible object storage for models storage
objectStorage:
  endpoint: ""
  region: ""
  bucket: speech-embed
  accessKey: ""
  secretKey: ""

# postgres has configuration for a PostgreSQL instance that will store data and
# metadata for customizations
postgres:
  # host is the hostname of server hosting the Postgres instance
  host: ""
  # port to connect to on the hostname
  port: 5432
  # loginDatabase is the database used to establish the connection before creating the customizations database
  loginDatabase: "postgres"
  # user is the existing user that will own the customizations database and be used at runtime
  user: ""
  # password is the password for user
  password: ""
  # databaseName is the database that will be created/used to hold data about customizations
  databaseName: "tts-customizations"

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      memory: 4Gi
      cpu: 1
      ephemeral-storage: 4Gi
    limits:
      memory: 4Gi
      cpu: 4
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      memory: 1Gi
      cpu: 0.2
      ephemeral-storage: 64Mi
    limits:
      memory: 1Gi
      cpu: 1
      ephemeral-storage: 64Mi
  customization:
    requests:
      memory: 2Gi
      cpu: 0.5
      ephemeral-storage: 2Gi
    limits:
      memory: 2Gi
      cpu: 1
      ephemeral-storage: 2Gi

# images configures which container images are used
# To pull by tag, set digest to the empty string
images:
  utils:
    repository: watson-tts-utils
    digest: sha256:5dbceaa956f3f0170b864df013b030376a96a9bf2973d1e52d5318106669b700
    tag: 1.12.0
  runtime:
    repository: watson-tts-runtime
    digest: sha256:d295e1e54d3bea7ab70bb27288e96d8773c4244349a24e3b96ce918f1b8695bb
    tag: 1.12.0
  haproxy:
    repository: watson-tts-haproxy
    digest: sha256:fec24fe24b8885184ddb2e8dcc67ecacb4f64779c70dcb3f3ec69baf8bf74006
    tag: 1.12.0
  customization:
    repository: watson-tts-customization
    digest: sha256:224afc4fad2e99e9bd7f3e746af39d9fd140db007e78187ac7b5ce02870a8721
    tag: 1.12.0
  catalog:
    repository: watson-tts-generic-models
    digest: sha256:3758401372231df1cca7adcdd0941446a718c168ab17e41eadcecb76ac9466e4
    tag: 1.12.0

# defaultModel will be used if no voice is included in the /synthesize request
defaultModel: en-US_AllisonV3Voice
# modelVersion sets the path within model storage where the catalog will be uploaded
modelVersion: "1.12.0"
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  deDEBirgitV3Voice:
    catalogName: de-DE_BirgitV3Voice
    repository: watson-tts-de-de-birgitv3voice
    digest: sha256:1a633ec10987bfc5bbebad7af1cd7559bca6322ab9cb76d8995e6bb19b096b54
    tag: 1.12.0
    enabled: false
  deDEDieterV3Voice:
    catalogName: de-DE_DieterV3Voice
    repository: watson-tts-de-de-dieterv3voice
    digest: sha256:a223c63c5243ca70ec55f6488801980523f107909d562ab6ee5d3d6cde081bf8
    tag: 1.12.0
    enabled: false
  deDEErikaV3Voice:
    catalogName: de-DE_ErikaV3Voice
    repository: watson-tts-de-de-erikav3voice
    digest: sha256:7e041ecae7178f3cb12bdfdd8bd6c9f1d6ed5be616f7afd546947469801ef96b
    tag: 1.12.0
    enabled: false
  enAUHeidiExpressive:
    catalogName: en-AU_HeidiExpressive
    repository: watson-tts-en-au-heidiexpressive
    digest: sha256:98161753fc99f6df73cbbe575f4402a99848b93b97f0c6c75ae2315cf49aafa3
    tag: 1.12.0
    enabled: false
  enAUJackExpressive:
    catalogName: en-AU_JackExpressive
    repository: watson-tts-en-au-jackexpressive
    digest: sha256:b9d741d8d75fc615215ddb583d9d7d91a42c313c3024ede98299a8e68680d0b7
    tag: 1.12.0
    enabled: false
  enGBCharlotteV3Voice:
    catalogName: en-GB_CharlotteV3Voice
    repository: watson-tts-en-gb-charlottev3voice
    digest: sha256:733f16e90e5586a42197820b72534c3b208601146c07b6c6b762677445b9f5ed
    tag: 1.12.0
    enabled: false
  enGBJamesV3Voice:
    catalogName: en-GB_JamesV3Voice
    repository: watson-tts-en-gb-jamesv3voice
    digest: sha256:f045f469a5bc2f9f2d2c4277b4ed2d0cf5b16634007ab5da763b103a22cab280
    tag: 1.12.0
    enabled: false
  enGBKateV3Voice:
    catalogName: en-GB_KateV3Voice
    repository: watson-tts-en-gb-katev3voice
    digest: sha256:f4af7fa8dffe89887e10d9fa6bcab160d4894464c96e3ec596a12c0f746d870e
    tag: 1.12.0
    enabled: false
  enUSAllisonExpressive:
    catalogName: en-US_AllisonExpressive
    repository: watson-tts-en-us-allisonexpressive
    digest: sha256:de3fc122b771c2101390f809b69ad161c8a57e4cb20dae90f843526130cd6382
    tag: 1.12.0
    enabled: false
  enUSAllisonV3Voice:
    catalogName: en-US_AllisonV3Voice
    repository: watson-tts-en-us-allisonv3voice
    digest: sha256:a799905f3ee70f53a9a024c612210baa21c1be539e0e915f27bf3971bfe6aa24
    tag: 1.12.0
    enabled: true
  enUSEmilyV3Voice:
    catalogName: en-US_EmilyV3Voice
    repository: watson-tts-en-us-emilyv3voice
    digest: sha256:2e0b449f10ed953ab339432829ed38e5b52ed8e31c89ad49bb4ceaff02cce844
    tag: 1.12.0
    enabled: false
  enUSEmmaExpressive:
    catalogName: en-US_EmmaExpressive
    repository: watson-tts-en-us-emmaexpressive
    digest: sha256:cc497c0536d2f0de9a26f811750056d24e0231668bd8fe69498f1c57b3d10e8b
    tag: 1.12.0
    enabled: false
  enUSHenryV3Voice:
    catalogName: en-US_HenryV3Voice
    repository: watson-tts-en-us-henryv3voice
    digest: sha256:7e3e5c1d23f1460a8a6abcfd63f4dd38f15caaada52c7ecbaa4e26ed2052b2e9
    tag: 1.12.0
    enabled: false
  enUSKevinV3Voice:
    catalogName: en-US_KevinV3Voice
    repository: watson-tts-en-us-kevinv3voice
    digest: sha256:2148396a7294f589107bd76d7cb1c971a849ee6d141771ca8148c9ac0cdeb297
    tag: 1.12.0
    enabled: false
  enUSLisaExpressive:
    catalogName: en-US_LisaExpressive
    repository: watson-tts-en-us-lisaexpressive
    digest: sha256:23b086b1c2b0d01970186a70f45b4deca29a9702e2a13f8688f19d0808188308
    tag: 1.12.0
    enabled: false
  enUSLisaV3Voice:
    catalogName: en-US_LisaV3Voice
    repository: watson-tts-en-us-lisav3voice
    digest: sha256:697a38bec75698663a8e49296e84c02c97e01ba65d5be2984d3e088fc1446ff1
    tag: 1.12.0
    enabled: false
  enUSMichaelExpressive:
    catalogName: en-US_MichaelExpressive
    repository: watson-tts-en-us-michaelexpressive
    digest: sha256:5a6096ca85508f34e688c1bc45c7b456adaa1459cf23c0ec3cdda6ec0ca4c290
    tag: 1.12.0
    enabled: false
  enUSMichaelV3Voice:
    catalogName: en-US_MichaelV3Voice
    repository: watson-tts-en-us-michaelv3voice
    digest: sha256:05a81f2be06ddce74ca596483e74375def1c1ebbfc4834a86b8a18ca77955201
    tag: 1.12.0
    enabled: true
  enUSOliviaV3Voice:
    catalogName: en-US_OliviaV3Voice
    repository: watson-tts-en-us-oliviav3voice
    digest: sha256:473f16b9de5f1d5fe8af0eb4bcc0954c58352960eb916ad394a4f4dc0054275f
    tag: 1.12.0
    enabled: false
  esESEnriqueV3Voice:
    catalogName: es-ES_EnriqueV3Voice
    repository: watson-tts-es-es-enriquev3voice
    digest: sha256:ba14a12d68fdc986fae4db01fb0c96121db5f14c61fe96993df57b88c9087a83
    tag: 1.12.0
    enabled: false
  esESLauraV3Voice:
    catalogName: es-ES_LauraV3Voice
    repository: watson-tts-es-es-laurav3voice
    digest: sha256:8098b0474af7676ecfeca0b51123739b679896db392dea016f5883de026f89de
    tag: 1.12.0
    enabled: false
  esLASofiaV3Voice:
    catalogName: es-LA_SofiaV3Voice
    repository: watson-tts-es-la-sofiav3voice
    digest: sha256:8b3f6c3a7f167c91dc2194f37f0b154be20376025d54a716353858a8728039e8
    tag: 1.12.0
    enabled: false
  esUSSofiaV3Voice:
    catalogName: es-US_SofiaV3Voice
    repository: watson-tts-es-us-sofiav3voice
    digest: sha256:da3238216e94705405f65cb80e12f4dade38c8bc10a00c764206e83dc6b65933
    tag: 1.12.0
    enabled: false
  frCALouiseV3Voice:
    catalogName: fr-CA_LouiseV3Voice
    repository: watson-tts-fr-ca-louisev3voice
    digest: sha256:022c57da5a0e9821ffa2e1da6dc0bfe99ae4d73d7372706f528564322e0e4bee
    tag: 1.12.0
    enabled: false
  frFRNicolasV3Voice:
    catalogName: fr-FR_NicolasV3Voice
    repository: watson-tts-fr-fr-nicolasv3voice
    digest: sha256:e586feb899239541ec5917ba71fdbcfe24cf2292528dec1d479dff484cf14d2f
    tag: 1.12.0
    enabled: false
  frFRReneeV3Voice:
    catalogName: fr-FR_ReneeV3Voice
    repository: watson-tts-fr-fr-reneev3voice
    digest: sha256:0a2905674001be4d963f568e18b75c705b716ced843edeac99cc3277634d3854
    tag: 1.12.0
    enabled: false
  itITFrancescaV3Voice:
    catalogName: it-IT_FrancescaV3Voice
    repository: watson-tts-it-it-francescav3voice
    digest: sha256:4e9b1c6885b1d77c5d1d7e2cec0acb5fe8d96f90b9d2aa0f2874b9a7c05b95ee
    tag: 1.12.0
    enabled: false
  jaJPEmiV3Voice:
    catalogName: ja-JP_EmiV3Voice
    repository: watson-tts-ja-jp-emiv3voice
    digest: sha256:002791539794d3f55e294e40e27168f2ce9af9155d14ace1d6ae7303eac08554
    tag: 1.12.0
    enabled: false
  koKRJinV3Voice:
    catalogName: ko-KR_JinV3Voice
    repository: watson-tts-ko-kr-jinv3voice
    digest: sha256:4027a75a8647f88d715498a60c62c953c409985e86b39b40da70fd2452e506ea
    tag: 1.12.0
    enabled: false
  nlNLMerelV3Voice:
    catalogName: nl-NL_MerelV3Voice
    repository: watson-tts-nl-nl-merelv3voice
    digest: sha256:71f6ebf0e17c6f708a4c0686a9dbd1e55de3bb3d67442440c618063cacb11e64
    tag: 1.12.0
    enabled: false
  ptBRIsabelaV3Voice:
    catalogName: pt-BR_IsabelaV3Voice
    repository: watson-tts-pt-br-isabelav3voice
    digest: sha256:5b5f05c4e180f8ef826294900c4c55efafe83977ab914faf8293fbffc8a72ce3
    tag: 1.12.0
    enabled: false
  tuneByExampleModel:
    catalogName: TuneByExampleModel
    repository: watson-tts-tunebyexamplemodel
    digest: sha256:6d0614a41527b2651963012214143bcccca978b237ff51fad8b464d4690000dc
    tag: 1.12.0
    enabled: true
