# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CJULPU
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# General Configuration

customizationEnabled: true

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP
# uploadModelConcurrency controls the number of models uploaded per upload job
# Jobs are run sequentially, so this affects the total duration.
uploadModelConcurrency: 5

# Service Dependencies

# objectStorage has configuration for an s3 compatible object storage for models storage
objectStorage:
  endpoint: ""
  region: ""
  bucket: speech-embed
  accessKey: ""
  secretKey: ""

# postgres has configuration for a PostgreSQL instance that will store data and
# metadata for customizations
postgres:
  # host is the hostname of server hosting the Postgres instance
  host: ""
  # port to connect to on the hostname
  port: 5432
  # loginDatabase is the database used to establish the connection before creating the customizations database
  loginDatabase: "postgres"
  # user is the existing user that will own the customizations database and be used at runtime
  user: ""
  # password is the password for user
  password: ""
  # databaseName is the database that will be created/used to hold data about customizations
  databaseName: "tts-customizations"

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      memory: 4Gi
      cpu: 1
      ephemeral-storage: 4Gi
    limits:
      memory: 4Gi
      cpu: 4
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      memory: 1Gi
      cpu: 0.2
      ephemeral-storage: 64Mi
    limits:
      memory: 1Gi
      cpu: 1
      ephemeral-storage: 64Mi
  customization:
    requests:
      memory: 2Gi
      cpu: 0.5
      ephemeral-storage: 2Gi
    limits:
      memory: 2Gi
      cpu: 1
      ephemeral-storage: 2Gi

# images configures which container images are used
# To pull by tag, set digest to the empty string
images:
  utils:
    repository: watson-tts-utils
    digest: sha256:9e235389be085ca7fe466dd24368655a826b53b530a9cf39acf1d8e9d3e716dd
    tag: 1.1.0
  runtime:
    repository: watson-tts-runtime
    digest: sha256:44c3e80bfbc4c539bb17556e9e764a073c180f16d9562c3d1cf099c9b0eb08c2
    tag: 1.1.0
  haproxy:
    repository: watson-tts-haproxy
    digest: sha256:6700ea7d48862aa9f01d26f5ae1453d10b08d626a5d741adf7e161c4abfee3b1
    tag: 1.1.0
  customization:
    repository: watson-tts-customization
    digest: sha256:8d6134663d1d4f1fd7799ce591142f1f683ae63cc11d0ea8ff7aaf20a6378e37
    tag: 1.1.0
  catalog:
    repository: watson-tts-generic-models
    digest: sha256:2ada4d0496e4424e6218999d27fd2065c75fa75a4b1d6302317367c1bd1adbca
    tag: 1.1.0

# defaultModel will be used if no voice is included in the /synthesize request
defaultModel: en-US_AllisonV3Voice
# modelVersion sets the path within model storage where the catalog will be uploaded
modelVersion: "1.1.0"
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  deDEBirgitV3Voice:
    catalogName: de-DE_BirgitV3Voice
    repository: watson-tts-de-de-birgitv3voice
    digest: sha256:01db4b7fbc457ed2c9fd6b042d70d8b5580f215fa62951fd86cd0968e1d4eb82
    tag: 1.1.0
    enabled: false
  deDEDieterV3Voice:
    catalogName: de-DE_DieterV3Voice
    repository: watson-tts-de-de-dieterv3voice
    digest: sha256:a2d65663c32e53d094b0c71c8b3731f749787cd6b7239fcc47d4c6e06e444aab
    tag: 1.1.0
    enabled: false
  deDEErikaV3Voice:
    catalogName: de-DE_ErikaV3Voice
    repository: watson-tts-de-de-erikav3voice
    digest: sha256:1cc8f2b017248bd73722ea456a6c33f20a3f4aa56dac33d369842bdd8084ee7a
    tag: 1.1.0
    enabled: false
  enGBCharlotteV3Voice:
    catalogName: en-GB_CharlotteV3Voice
    repository: watson-tts-en-gb-charlottev3voice
    digest: sha256:2eaf3eede853f3a2586b099e9d05b5a69e1b5fd4181ef5a7de2495b3e2386e2a
    tag: 1.1.0
    enabled: false
  enGBJamesV3Voice:
    catalogName: en-GB_JamesV3Voice
    repository: watson-tts-en-gb-jamesv3voice
    digest: sha256:51c58bcefa4245e37811d8440521806318231db927efddf7b5744aef056348d4
    tag: 1.1.0
    enabled: false
  enGBKateV3Voice:
    catalogName: en-GB_KateV3Voice
    repository: watson-tts-en-gb-katev3voice
    digest: sha256:ae65a3c3fb196d0f2df5c20c03321303d1cbb09ad61a4a12095df5ff6c144f89
    tag: 1.1.0
    enabled: false
  enUSAllisonV3Voice:
    catalogName: en-US_AllisonV3Voice
    repository: watson-tts-en-us-allisonv3voice
    digest: sha256:c1b1968ff9241737b53e8537894cf44c18dd9374a1eb686b6c519c7bb31a3ef6
    tag: 1.1.0
    enabled: true
  enUSEmilyV3Voice:
    catalogName: en-US_EmilyV3Voice
    repository: watson-tts-en-us-emilyv3voice
    digest: sha256:f00fc7307e0f09041177f1c5eaa15634a55cb68087fa1b49d171f05fb97f7ba3
    tag: 1.1.0
    enabled: false
  enUSHenryV3Voice:
    catalogName: en-US_HenryV3Voice
    repository: watson-tts-en-us-henryv3voice
    digest: sha256:6d41acd7485d307a44a69f69ab9ad959bf1d1ba563790d101b27db95c8731559
    tag: 1.1.0
    enabled: false
  enUSKevinV3Voice:
    catalogName: en-US_KevinV3Voice
    repository: watson-tts-en-us-kevinv3voice
    digest: sha256:58bc866f5a4403b48c045fe3e177941d0cb870c95d32217534b7bb8758bd359b
    tag: 1.1.0
    enabled: false
  enUSLisaV3Voice:
    catalogName: en-US_LisaV3Voice
    repository: watson-tts-en-us-lisav3voice
    digest: sha256:73ed69b321fc9a7dda4b4180f6416f8272b40d826d06018c1b71e9ae37a386aa
    tag: 1.1.0
    enabled: false
  enUSMichaelV3Voice:
    catalogName: en-US_MichaelV3Voice
    repository: watson-tts-en-us-michaelv3voice
    digest: sha256:75a05cc2a8f3955dc051193e433cc7cf83ec9424d176650ea40453f5fabc6645
    tag: 1.1.0
    enabled: true
  enUSOliviaV3Voice:
    catalogName: en-US_OliviaV3Voice
    repository: watson-tts-en-us-oliviav3voice
    digest: sha256:6a77a862367f73c8007929ab3eefcbc3caeaef7a21c8a1099b0e7ff0aa2a2ce4
    tag: 1.1.0
    enabled: false
  esESEnriqueV3Voice:
    catalogName: es-ES_EnriqueV3Voice
    repository: watson-tts-es-es-enriquev3voice
    digest: sha256:5a02c1ce912997017aabf248bb36874c13601d0710f2573ad551d4d7c875e756
    tag: 1.1.0
    enabled: false
  esESLauraV3Voice:
    catalogName: es-ES_LauraV3Voice
    repository: watson-tts-es-es-laurav3voice
    digest: sha256:e00af9c90acdfb8eaa383a3b7ad810ee7fbe65d7409e40402e1cd80fdc91a0e3
    tag: 1.1.0
    enabled: false
  esLASofiaV3Voice:
    catalogName: es-LA_SofiaV3Voice
    repository: watson-tts-es-la-sofiav3voice
    digest: sha256:f6b1fc23855c5e329b4af0194b00280a3acea49e4a538f82cd71916c625e7c59
    tag: 1.1.0
    enabled: false
  esUSSofiaV3Voice:
    catalogName: es-US_SofiaV3Voice
    repository: watson-tts-es-us-sofiav3voice
    digest: sha256:54257abb4cfccbeee8d78589eb43a12d766aa822044bdf6067d948b554b0f486
    tag: 1.1.0
    enabled: false
  frCALouiseV3Voice:
    catalogName: fr-CA_LouiseV3Voice
    repository: watson-tts-fr-ca-louisev3voice
    digest: sha256:5266d949d6428c1b8d578bc8ef0690cfee7b95dedaae411af2e5d8cf3df0963f
    tag: 1.1.0
    enabled: false
  frFRNicolasV3Voice:
    catalogName: fr-FR_NicolasV3Voice
    repository: watson-tts-fr-fr-nicolasv3voice
    digest: sha256:94bf98acc951ca92d2af021e788ec03ea9ff24cf4b690e4881e4302ff2080d7f
    tag: 1.1.0
    enabled: false
  frFRReneeV3Voice:
    catalogName: fr-FR_ReneeV3Voice
    repository: watson-tts-fr-fr-reneev3voice
    digest: sha256:e11e4b2e609ee1c67352ff541c636590ce1056c86be0fbdc95265e92ae4fe6a5
    tag: 1.1.0
    enabled: false
  itITFrancescaV3Voice:
    catalogName: it-IT_FrancescaV3Voice
    repository: watson-tts-it-it-francescav3voice
    digest: sha256:70ae8d4b0de1c7e5c14398d1063eb5e623e246d4bfd1c161023e844ded7346c7
    tag: 1.1.0
    enabled: false
  jaJPEmiV3Voice:
    catalogName: ja-JP_EmiV3Voice
    repository: watson-tts-ja-jp-emiv3voice
    digest: sha256:1f3f2c80fd7eb97c954e59f6786f7a862e03403f7e4c2a4fd3abd45f7eba3615
    tag: 1.1.0
    enabled: false
  ptBRIsabelaV3Voice:
    catalogName: pt-BR_IsabelaV3Voice
    repository: watson-tts-pt-br-isabelav3voice
    digest: sha256:4def739a18992f8d53f5e259e96bbc1fd96595d9ca76df623468f8530b86b623
    tag: 1.1.0
    enabled: false
