apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-watson-stt-embed.runtime.fullname" . }}
  labels:
    {{- include "ibm-watson-stt-embed.runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    {{- include "ibm-watson-stt-embed.runtime.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 1443
