{{- if not (eq .Values.license true) }}
  {{- fail "Product licenses must be read and accepted. Then set `license` to true" }}
{{- end }}

{{- /* Construct the list of model images to use in initContainers */}}
{{- $enabledModels := (include "ibm-embed-helpers.enabledModelImageConfigs" .) | fromYamlArray }}

{{- /* Construct the list of model ids */}}
{{- $modelsList := (list) }}
{{- range $enabledModels }}
  {{- $modelsList = append $modelsList .catalogName }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibm-watson-stt-embed-runtime.fullname" . }}
  labels:
    {{- include "ibm-watson-stt-embed-runtime.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ibm-watson-stt-embed-runtime.selectorLabels" . | nindent 6 }}
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        {{- include "ibm-watson-stt-embed-runtime.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}

      {{- include "ibm-embed-helpers.podSecurityContext" . | nindent 6 -}}

      initContainers:
      - name: catalog
        image: {{ include "ibm-embed-helpers.imageReference" (list . .Values.images.catalog) }}
        {{- include "ibm-embed-helpers.containerSecurityContext" . | nindent 8 -}}
        env:
        - name: ACCEPT_LICENSE
          value: {{ $.Values.license | quote }}
        resources:
          {{- $.Values.resources.runtime | toYaml | nindent 10 }}
        # use args to not override license entrypoint
        args: ["cp", "catalog.json", "/opt/ibm/chuck.x86_64/var/catalog.json"]
        volumeMounts:
        - name: chuck-var
          mountPath: /opt/ibm/chuck.x86_64/var

      {{- range $model := $enabledModels }}
      - name: {{ $model.repository }}
        image: {{ include "ibm-embed-helpers.imageReference" (list $ $model) }}
        {{- include "ibm-embed-helpers.containerSecurityContext" $ | nindent 8 -}}
        env:
        - name: ACCEPT_LICENSE
          value: {{ $.Values.license | quote }}
        resources:
          {{- $.Values.resources.runtime | toYaml | nindent 10 }}
        # use args to not override license entrypoint
        args:
        - sh
        - -c
        - cp model/* /models/pool2
        volumeMounts:
        - name: chuck-models
          mountPath: /models/pool2
      {{- end }}

      - name: prepare-models
        image: {{ include "ibm-embed-helpers.imageReference" (list . .Values.images.runtime) }}
        {{- include "ibm-embed-helpers.containerSecurityContext" . | nindent 8 -}}
        # use args to not override license entrypoint
        args: ["prepare_models.sh"]
        env:
        - name: ACCEPT_LICENSE
          value: {{ $.Values.license | quote }}
        - name: CATALOG_PATH
          value: "var/catalog.json"
        - name: MODELS
          value: {{ join "," $modelsList }}
        - name: DEFAULT_MODEL
          value: {{ .Values.defaultModel | quote }}
        resources:
          {{- .Values.resources.runtime | toYaml | nindent 10 }}
        volumeMounts:
        - name: chuck-var
          mountPath: /opt/ibm/chuck.x86_64/var
        - name: chuck-logs
          mountPath: /opt/ibm/chuck.x86_64/logs
        - name: chuck-models
          mountPath: /models/pool2
        - name: tmp
          mountPath: /tmp

      containers:
      - name: runtime
        image: {{ include "ibm-embed-helpers.imageReference" (list . .Values.images.runtime) }}
        {{- include "ibm-embed-helpers.containerSecurityContext" . | nindent 8 -}}
        resources:
          {{- .Values.resources.runtime | toYaml | nindent 10 }}
        env:
        - name: ACCEPT_LICENSE
          value: {{ $.Values.license | quote }}
        - name: CATALOG_PATH
          value: "var/catalog.json"
        - name: MODELS
          value: {{ join "," $modelsList }}
        - name: DEFAULT_MODEL
          value: {{ .Values.defaultModel | quote }}
        - name: RESOURCES_CPU
          valueFrom:
            resourceFieldRef:
              containerName: runtime
              resource: requests.cpu
        - name: RESOURCES_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: runtime
              resource: requests.memory
        ports:
        - containerPort: 1080
        startupProbe:
          tcpSocket:
            port: 1080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1080
          periodSeconds: 10
        readinessProbe:
          httpGet:
             path: /v1/miniHealthCheck
             port: 1080
          periodSeconds: 10
        volumeMounts:
        - name: chuck-var
          mountPath: /opt/ibm/chuck.x86_64/var
        - name: chuck-logs
          mountPath: /opt/ibm/chuck.x86_64/logs
        - name: tmp
          mountPath: /tmp
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "15"

      - name: haproxy
        image: {{ include "ibm-embed-helpers.imageReference" (list . .Values.images.haproxy) }}
        {{- include "ibm-embed-helpers.containerSecurityContext" . | nindent 8 -}}
        resources:
          {{- .Values.resources.haproxy | toYaml | nindent 10 }}
        env:
        - name: ACCEPT_LICENSE
          value: {{ .Values.license | quote }}
        - name: TLS_SERVER_CERT_FILE
          value: /etc/ssl/private/server/tls.crt
        - name: TLS_SERVER_KEY_FILE
          value: /etc/ssl/private/server/tls.key
        ports:
        - containerPort: 1443
        startupProbe:
          tcpSocket:
            port: 1443
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1443
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1
            port: 1443
            scheme: HTTPS
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/ssl/private/server
          name: server-tls
        - name: tmp
          mountPath: /tmp

      volumes:
        - name: chuck-var
          emptyDir: {}
        - name: chuck-models
          emptyDir: {}
        - name: chuck-cache
          emptyDir: {}
        - name: chuck-logs
          emptyDir: {}
        - name: server-tls
          secret:
            secretName: {{ include "ibm-watson-stt-embed-runtime.fullname" . }}-tls-server
        - name: tmp
          emptyDir: {}

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values:
                  - "amd64"
