# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CJULPU
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-tts-runtime
    digest: sha256:512ab2293e23566e8466606ebef758068ee0b68ad1a7395b4bb5bccb77912b28
    tag: 1.9.0
  haproxy:
    repository: watson-tts-haproxy
    digest: sha256:ca9a1f56bef2a6f2088fee33c15985096c5a54f2060bada578b03a1c092e4d68
    tag: 1.9.0
  catalog:
    repository: watson-tts-generic-models
    digest: sha256:aa57f6a008c70f4dd0611f692c83c03f50ed2a9c4c461a92eebc202e88796fb6
    tag: 1.9.0

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 1
      memory: 4Gi
      ephemeral-storage: 4Gi
    limits:
      cpu: 4
      memory: 4Gi
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no voice is included in the /synthesize request
defaultModel: en-US_AllisonV3Voice
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  deDEBirgitV3Voice:
    catalogName: de-DE_BirgitV3Voice
    repository: watson-tts-de-de-birgitv3voice
    digest: sha256:da6e214424d33d96f55e53e0dac335dd4bb70351a4c8b3e8966fa0ee6ce4ca98
    tag: 1.9.0
    enabled: false
  deDEDieterV3Voice:
    catalogName: de-DE_DieterV3Voice
    repository: watson-tts-de-de-dieterv3voice
    digest: sha256:a2accdb55deed84bf62f5e88c032bff74acf6b36cc6b2bdd83785cde880b340b
    tag: 1.9.0
    enabled: false
  deDEErikaV3Voice:
    catalogName: de-DE_ErikaV3Voice
    repository: watson-tts-de-de-erikav3voice
    digest: sha256:05d23f9e38b2df25c96406582804a2a319d66cea65162c8ed4434edf69d97ade
    tag: 1.9.0
    enabled: false
  enAUHeidiExpressive:
    catalogName: en-AU_HeidiExpressive
    repository: watson-tts-en-au-heidiexpressive
    digest: sha256:237aa51030fed640d4048c9fc272b31cff6ad1d1453bed01298e29ae73079564
    tag: 1.9.0
    enabled: false
  enAUJackExpressive:
    catalogName: en-AU_JackExpressive
    repository: watson-tts-en-au-jackexpressive
    digest: sha256:79b8ed0a3dcb2d8c992fe837c5af7dac9521edfb16136411c8d79656900efba4
    tag: 1.9.0
    enabled: false
  enGBCharlotteV3Voice:
    catalogName: en-GB_CharlotteV3Voice
    repository: watson-tts-en-gb-charlottev3voice
    digest: sha256:5ed430b50d653ff5ef1229a95f2b095ca722c7261cc8b7dfe9926445701a4f35
    tag: 1.9.0
    enabled: false
  enGBJamesV3Voice:
    catalogName: en-GB_JamesV3Voice
    repository: watson-tts-en-gb-jamesv3voice
    digest: sha256:a8258acfe89d1897db9f3a9b7d685884044278f0f918e011d96c11793ba2cff8
    tag: 1.9.0
    enabled: false
  enGBKateV3Voice:
    catalogName: en-GB_KateV3Voice
    repository: watson-tts-en-gb-katev3voice
    digest: sha256:f4802f1e210d3a7d5ae0e529a2c8501bec85690fc409d3389d2486f29cfbb0a0
    tag: 1.9.0
    enabled: false
  enUSAllisonExpressive:
    catalogName: en-US_AllisonExpressive
    repository: watson-tts-en-us-allisonexpressive
    digest: sha256:c5f7a5c2cd2b96111baa814c30a2b19eaaa630e72e2800b6db83bd45d57342b6
    tag: 1.9.0
    enabled: false
  enUSAllisonV3Voice:
    catalogName: en-US_AllisonV3Voice
    repository: watson-tts-en-us-allisonv3voice
    digest: sha256:3e4c7ce55d5ccf8fe20d26a1ace75e5339391dabb312450e657b9054c11ce59f
    tag: 1.9.0
    enabled: true
  enUSEmilyV3Voice:
    catalogName: en-US_EmilyV3Voice
    repository: watson-tts-en-us-emilyv3voice
    digest: sha256:d405c09c92fdc313658558331335ce3a46befbedcf5b56b5a4c678c0fa51aa6e
    tag: 1.9.0
    enabled: false
  enUSEmmaExpressive:
    catalogName: en-US_EmmaExpressive
    repository: watson-tts-en-us-emmaexpressive
    digest: sha256:e8d4905c60eefaa37f91abd7ad80fe3d94b5b8e5b77a3a43eac7b69f06693257
    tag: 1.9.0
    enabled: false
  enUSHenryV3Voice:
    catalogName: en-US_HenryV3Voice
    repository: watson-tts-en-us-henryv3voice
    digest: sha256:6c617444362383b7628ae81fc4030e8ec1a537a45af4355f7405138477b9c87e
    tag: 1.9.0
    enabled: false
  enUSKevinV3Voice:
    catalogName: en-US_KevinV3Voice
    repository: watson-tts-en-us-kevinv3voice
    digest: sha256:5a50a727ad773d25eacfa18767a9648de3de7b85214c7c481044df1ffb0778ba
    tag: 1.9.0
    enabled: false
  enUSLisaExpressive:
    catalogName: en-US_LisaExpressive
    repository: watson-tts-en-us-lisaexpressive
    digest: sha256:6b86364154f5146d1e0e9f5668f95d46063e53d84a2998283288b45e8c790a24
    tag: 1.9.0
    enabled: false
  enUSLisaV3Voice:
    catalogName: en-US_LisaV3Voice
    repository: watson-tts-en-us-lisav3voice
    digest: sha256:1d56a0915330895269848f1c018fadcac9bf09cb4cb8baebb1a8c47c15c838b8
    tag: 1.9.0
    enabled: false
  enUSMichaelExpressive:
    catalogName: en-US_MichaelExpressive
    repository: watson-tts-en-us-michaelexpressive
    digest: sha256:d04491397bdcf45ecc49f2c9bfbd188076ef14184edbdcf2c360ca7ac208e05c
    tag: 1.9.0
    enabled: false
  enUSMichaelV3Voice:
    catalogName: en-US_MichaelV3Voice
    repository: watson-tts-en-us-michaelv3voice
    digest: sha256:f070268c1387d09fb6d537266177a8accd0b8cb80489bf0ed0120c5165f5eb73
    tag: 1.9.0
    enabled: true
  enUSOliviaV3Voice:
    catalogName: en-US_OliviaV3Voice
    repository: watson-tts-en-us-oliviav3voice
    digest: sha256:05ea99f9f7cefc8483a292a1ea8bbf97fc3c6657d8468d09533b8a1a345c2581
    tag: 1.9.0
    enabled: false
  esESEnriqueV3Voice:
    catalogName: es-ES_EnriqueV3Voice
    repository: watson-tts-es-es-enriquev3voice
    digest: sha256:e24f616ee804ae299c3a064dfc9859abbc5dc708190553fd6433d3fdfc477702
    tag: 1.9.0
    enabled: false
  esESLauraV3Voice:
    catalogName: es-ES_LauraV3Voice
    repository: watson-tts-es-es-laurav3voice
    digest: sha256:dc114c8777243a9545744a49d5b889a29a7d7232a79148f37619eeeeaaed26da
    tag: 1.9.0
    enabled: false
  esLASofiaV3Voice:
    catalogName: es-LA_SofiaV3Voice
    repository: watson-tts-es-la-sofiav3voice
    digest: sha256:4aa788e62040e1e0ce0c8b8fffb227f32b9cca7a98d6f6a4e2cdf54ebe02e168
    tag: 1.9.0
    enabled: false
  esUSSofiaV3Voice:
    catalogName: es-US_SofiaV3Voice
    repository: watson-tts-es-us-sofiav3voice
    digest: sha256:39f6cc0fb625e6bfcf0fb3a2da17feddb1f189a7a1384bc4ea4b15c2f9af8048
    tag: 1.9.0
    enabled: false
  frCALouiseV3Voice:
    catalogName: fr-CA_LouiseV3Voice
    repository: watson-tts-fr-ca-louisev3voice
    digest: sha256:999a8ac49a8702eb299fd49da4b8a2cc3daf4bc5520dc799491ea5c20bf80db4
    tag: 1.9.0
    enabled: false
  frFRNicolasV3Voice:
    catalogName: fr-FR_NicolasV3Voice
    repository: watson-tts-fr-fr-nicolasv3voice
    digest: sha256:0df5b058eb6ca22782a657d5c09716a648cec6e316ef1f6802a08c327cb968b7
    tag: 1.9.0
    enabled: false
  frFRReneeV3Voice:
    catalogName: fr-FR_ReneeV3Voice
    repository: watson-tts-fr-fr-reneev3voice
    digest: sha256:ed44572ec9b0da188fc6b80b8fc3757733ab76c60ea5afff20fa8ddd8e4b1762
    tag: 1.9.0
    enabled: false
  itITFrancescaV3Voice:
    catalogName: it-IT_FrancescaV3Voice
    repository: watson-tts-it-it-francescav3voice
    digest: sha256:c99d2f65e46e01ab9e9de00bd551376ca7f7daf37f7658c02e7602fbd5e6fbce
    tag: 1.9.0
    enabled: false
  jaJPEmiV3Voice:
    catalogName: ja-JP_EmiV3Voice
    repository: watson-tts-ja-jp-emiv3voice
    digest: sha256:7afedb9883a9e29a44a69e230917a0c608247a8553c8814e459b14c2ca5c25a3
    tag: 1.9.0
    enabled: false
  koKRJinV3Voice:
    catalogName: ko-KR_JinV3Voice
    repository: watson-tts-ko-kr-jinv3voice
    digest: sha256:75eee054407a9a317bb6dd54485c507e30db405440d5e95d4bd2722a810def49
    tag: 1.9.0
    enabled: false
  nlNLMerelV3Voice:
    catalogName: nl-NL_MerelV3Voice
    repository: watson-tts-nl-nl-merelv3voice
    digest: sha256:2ce41a2cfc9d74255b947920d2368c927f7130c9857308312565236762948938
    tag: 1.9.0
    enabled: false
  ptBRIsabelaV3Voice:
    catalogName: pt-BR_IsabelaV3Voice
    repository: watson-tts-pt-br-isabelav3voice
    digest: sha256:221db18b39660bf7548fe7f87e473c80a9252534a1056e69f9d17797c76ed2c0
    tag: 1.9.0
    enabled: false
