# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CJULPU
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-tts-runtime
    digest: sha256:c3ff8c8bb4f284df4b6b5a7f9225e2010e8dc1c13d253ce9f5fc206a93e9824a
    tag: 1.4.0
  haproxy:
    repository: watson-tts-haproxy
    digest: sha256:852643f5c46088f7cda6097ca012faf83f8e5313ed5d741d7f377aa3e61f17b8
    tag: 1.4.0
  catalog:
    repository: watson-tts-generic-models
    digest: sha256:dacc3f8b12e567c989db514b26d24afa74c6644474df027ff1a1ee0e44a1754f
    tag: 1.4.0

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 1
      memory: 4Gi
      ephemeral-storage: 4Gi
    limits:
      cpu: 4
      memory: 4Gi
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no voice is included in the /synthesize request
defaultModel: en-US_AllisonV3Voice
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  deDEBirgitV3Voice:
    catalogName: de-DE_BirgitV3Voice
    repository: watson-tts-de-de-birgitv3voice
    digest: sha256:1ed0d479ebece9a2d32d7ae990849032f93e6cb21230f8f5176cbdd023a76c62
    tag: 1.4.0
    enabled: false
  deDEDieterV3Voice:
    catalogName: de-DE_DieterV3Voice
    repository: watson-tts-de-de-dieterv3voice
    digest: sha256:1ae4110692e5c8a9b2dc338efd72b52e4b35cf623edbf7300a008e9036ec56ea
    tag: 1.4.0
    enabled: false
  deDEErikaV3Voice:
    catalogName: de-DE_ErikaV3Voice
    repository: watson-tts-de-de-erikav3voice
    digest: sha256:c46463d6e8fcc69678c70e39418c69a6de13b78efb7d98f782b9826b904f23b5
    tag: 1.4.0
    enabled: false
  enGBCharlotteV3Voice:
    catalogName: en-GB_CharlotteV3Voice
    repository: watson-tts-en-gb-charlottev3voice
    digest: sha256:e2fe689f493d3703501e0650e43753c0833ccc7b20933f84bb64d8b72be68c55
    tag: 1.4.0
    enabled: false
  enGBJamesV3Voice:
    catalogName: en-GB_JamesV3Voice
    repository: watson-tts-en-gb-jamesv3voice
    digest: sha256:35eb0e46bef7192e51446a61a983556eb57e3dcf7c0fdd863045a531493edba8
    tag: 1.4.0
    enabled: false
  enGBKateV3Voice:
    catalogName: en-GB_KateV3Voice
    repository: watson-tts-en-gb-katev3voice
    digest: sha256:658d7f5d3da34b2332c00b471a87f2c5ea914c3faa426eada33d4094b47c6e25
    tag: 1.4.0
    enabled: false
  enUSAllisonExpressive:
    catalogName: en-US_AllisonExpressive
    repository: watson-tts-en-us-allisonexpressive
    digest: sha256:ee7521d002aa530a538ec42b622c316dc5b6dd8f78fadede75870623d9725bf2
    tag: 1.4.0
    enabled: false
  enUSAllisonV3Voice:
    catalogName: en-US_AllisonV3Voice
    repository: watson-tts-en-us-allisonv3voice
    digest: sha256:f3aa1fa9017785a864551a7649a2da25eb2d6cbfae32d216b0567777b721bb72
    tag: 1.4.0
    enabled: true
  enUSEmilyV3Voice:
    catalogName: en-US_EmilyV3Voice
    repository: watson-tts-en-us-emilyv3voice
    digest: sha256:070237ccdcfc464e70c744461c039f695b8340e35243098945a0a60264716f20
    tag: 1.4.0
    enabled: false
  enUSEmmaExpressive:
    catalogName: en-US_EmmaExpressive
    repository: watson-tts-en-us-emmaexpressive
    digest: sha256:3989ad73b98ba1c59a84315f97d23d346452c2a1c0728dca03d2e0b4e03cf926
    tag: 1.4.0
    enabled: false
  enUSHenryV3Voice:
    catalogName: en-US_HenryV3Voice
    repository: watson-tts-en-us-henryv3voice
    digest: sha256:839967eef609c74e6397dd6d7061a92e892d515ff98897dfc6aa158af2d41d37
    tag: 1.4.0
    enabled: false
  enUSKevinV3Voice:
    catalogName: en-US_KevinV3Voice
    repository: watson-tts-en-us-kevinv3voice
    digest: sha256:5b83959846860571860420e54ab49a3fb52762f3714b0bdbb1ea45f039907df6
    tag: 1.4.0
    enabled: false
  enUSLisaExpressive:
    catalogName: en-US_LisaExpressive
    repository: watson-tts-en-us-lisaexpressive
    digest: sha256:a5997ab5077e7b1335e5540440f3c34d6d2e9db56df512a9bda8e063f7f111f3
    tag: 1.4.0
    enabled: false
  enUSLisaV3Voice:
    catalogName: en-US_LisaV3Voice
    repository: watson-tts-en-us-lisav3voice
    digest: sha256:6f141ea8572306cac48b30a48a485f11efab00cbed5617d7f62cbe870bb7d064
    tag: 1.4.0
    enabled: false
  enUSMichaelExpressive:
    catalogName: en-US_MichaelExpressive
    repository: watson-tts-en-us-michaelexpressive
    digest: sha256:7181db54117806fb66cb740983bd5d372ade3f25a828d0dd46ee5f8a2860d4c3
    tag: 1.4.0
    enabled: false
  enUSMichaelV3Voice:
    catalogName: en-US_MichaelV3Voice
    repository: watson-tts-en-us-michaelv3voice
    digest: sha256:32d2d377a48c203703228fc2d2f6edd86248e0fa05979cfe7381c8ca96c0213c
    tag: 1.4.0
    enabled: true
  enUSOliviaV3Voice:
    catalogName: en-US_OliviaV3Voice
    repository: watson-tts-en-us-oliviav3voice
    digest: sha256:1671bbc22e5768c673a7eac3c10ab74ec92cb467a61a94723de5047e176f5b8f
    tag: 1.4.0
    enabled: false
  esESEnriqueV3Voice:
    catalogName: es-ES_EnriqueV3Voice
    repository: watson-tts-es-es-enriquev3voice
    digest: sha256:8dca64deb8000ad9be038a0ee01d72800d4ad92107aaa3632068133118364e0f
    tag: 1.4.0
    enabled: false
  esESLauraV3Voice:
    catalogName: es-ES_LauraV3Voice
    repository: watson-tts-es-es-laurav3voice
    digest: sha256:42c4cb29998bb8f92f196d26366190f15a2cde3cae092577c9e69990b301c008
    tag: 1.4.0
    enabled: false
  esLASofiaV3Voice:
    catalogName: es-LA_SofiaV3Voice
    repository: watson-tts-es-la-sofiav3voice
    digest: sha256:76c5852c111e19db5d030ad714648daad02a61c4b71dfbdbcee15c272ff45e7e
    tag: 1.4.0
    enabled: false
  esUSSofiaV3Voice:
    catalogName: es-US_SofiaV3Voice
    repository: watson-tts-es-us-sofiav3voice
    digest: sha256:d0bd5c1ea1d9587844fe2fe7564e31acc82f51a37b9fd3491f89857186ef25be
    tag: 1.4.0
    enabled: false
  frCALouiseV3Voice:
    catalogName: fr-CA_LouiseV3Voice
    repository: watson-tts-fr-ca-louisev3voice
    digest: sha256:e08f575e9ef7087220d475c963c817d8177ce520a037830f16fd5b8ade943332
    tag: 1.4.0
    enabled: false
  frFRNicolasV3Voice:
    catalogName: fr-FR_NicolasV3Voice
    repository: watson-tts-fr-fr-nicolasv3voice
    digest: sha256:6349f11c989809cdf822423c3c7ff43e9a42725ce50a821d3581bac42881eb94
    tag: 1.4.0
    enabled: false
  frFRReneeV3Voice:
    catalogName: fr-FR_ReneeV3Voice
    repository: watson-tts-fr-fr-reneev3voice
    digest: sha256:2aab800aa8c30e1a0311e7527f7a12ab165c806d1fb0a3cca3cdd2ef25fe8433
    tag: 1.4.0
    enabled: false
  itITFrancescaV3Voice:
    catalogName: it-IT_FrancescaV3Voice
    repository: watson-tts-it-it-francescav3voice
    digest: sha256:22b17fc1beabcc5db6a47b5184e19dbf382a36ff2d9f9cb1e86c8530785cb9cc
    tag: 1.4.0
    enabled: false
  jaJPEmiV3Voice:
    catalogName: ja-JP_EmiV3Voice
    repository: watson-tts-ja-jp-emiv3voice
    digest: sha256:cf3cf1113a32d0af01ad8640a274706db657ae5874c79a8250cb28060ec7cd15
    tag: 1.4.0
    enabled: false
  ptBRIsabelaV3Voice:
    catalogName: pt-BR_IsabelaV3Voice
    repository: watson-tts-pt-br-isabelav3voice
    digest: sha256:3bcec0ad7931d71251892349eaa3dd6449e9d79b12a9cbad65164f5b0baf5d28
    tag: 1.4.0
    enabled: false
