# By setting license to true you indicate that you have read and agree to the
# license agreements:
# https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DAJI-CJULPU
license: false

# Common Configuration

nameOverride: ""
fullnameOverride: ""

containerRegistry: cp.icr.io/cp/ai
imagePullSecrets:
  - name: ibm-entitlement-key

# readOnlyRootFilesystem controls the setting in the container security context
readOnlyRootFilesystem: true

serviceType: ClusterIP

# images configures which container images are used
# To pull by tag only, set digest to the empty string
images:
  runtime:
    repository: watson-tts-runtime
    digest: sha256:c25748bd79515ddfebf3388b0d18a2cdcb8cbca8feca2f667ed63f24ed115123
    tag: 1.9.1
  haproxy:
    repository: watson-tts-haproxy
    digest: sha256:bc3322129984574a84a3531a9526c25de06aac8aa0d6f1fb12af07c76d96e14c
    tag: 1.9.1
  catalog:
    repository: watson-tts-generic-models
    digest: sha256:6761dedf5d9a47e463c418e4931e3dabf6a9bab1d16b253894883f527b34bf3d
    tag: 1.9.1

# resources sets per-container resource allocations
resources:
  runtime:
    requests:
      cpu: 1
      memory: 4Gi
      ephemeral-storage: 4Gi
    limits:
      cpu: 4
      memory: 4Gi
      ephemeral-storage: 4Gi
  haproxy:
    requests:
      cpu: 0.2
      memory: 1Gi
      ephemeral-storage: 64Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 64Mi

# defaultModel will be used if no voice is included in the /synthesize request
defaultModel: en-US_AllisonV3Voice
# models has configuration for model container images and model enablement
# To pull by tag, set digest to the empty string
models:
  deDEBirgitV3Voice:
    catalogName: de-DE_BirgitV3Voice
    repository: watson-tts-de-de-birgitv3voice
    digest: sha256:59825c7121498169e03f2cfb4e21b876f2823772db7c81731fbdc0bd30eb69cb
    tag: 1.9.1
    enabled: false
  deDEDieterV3Voice:
    catalogName: de-DE_DieterV3Voice
    repository: watson-tts-de-de-dieterv3voice
    digest: sha256:0123df79dfe1860d2a75992c94bab27e3d51afa2200ee151e801be815fc18411
    tag: 1.9.1
    enabled: false
  deDEErikaV3Voice:
    catalogName: de-DE_ErikaV3Voice
    repository: watson-tts-de-de-erikav3voice
    digest: sha256:ec561360c4b961fe65a478863728f4e1ad5c121b5f3ce2cf438845015c51a386
    tag: 1.9.1
    enabled: false
  enAUHeidiExpressive:
    catalogName: en-AU_HeidiExpressive
    repository: watson-tts-en-au-heidiexpressive
    digest: sha256:680e30dfef1cf4ecc1376c7e9691525a03328708e41a22e848743a7327ec93ce
    tag: 1.9.1
    enabled: false
  enAUJackExpressive:
    catalogName: en-AU_JackExpressive
    repository: watson-tts-en-au-jackexpressive
    digest: sha256:e01726e248aa4335b72a362d65e037dc87c2348c4f554d1656b92ede6355ea99
    tag: 1.9.1
    enabled: false
  enGBCharlotteV3Voice:
    catalogName: en-GB_CharlotteV3Voice
    repository: watson-tts-en-gb-charlottev3voice
    digest: sha256:450d67df03e545794510c92a218fd7b52f4f41de8491d3382ded45bf0b9129e9
    tag: 1.9.1
    enabled: false
  enGBJamesV3Voice:
    catalogName: en-GB_JamesV3Voice
    repository: watson-tts-en-gb-jamesv3voice
    digest: sha256:6465aed82043d21d74a921c7b2586b93c3e4de582cd3774fc021a197c8ab9749
    tag: 1.9.1
    enabled: false
  enGBKateV3Voice:
    catalogName: en-GB_KateV3Voice
    repository: watson-tts-en-gb-katev3voice
    digest: sha256:43c3965faed2be4d7d37cb631c13ce21972f4f4d6b14c9a04a3bfa3464b95742
    tag: 1.9.1
    enabled: false
  enUSAllisonExpressive:
    catalogName: en-US_AllisonExpressive
    repository: watson-tts-en-us-allisonexpressive
    digest: sha256:0afc4c05bd56d318f110d03eb0b1b39d9c146017c84480782a451a3fbb72006b
    tag: 1.9.1
    enabled: false
  enUSAllisonV3Voice:
    catalogName: en-US_AllisonV3Voice
    repository: watson-tts-en-us-allisonv3voice
    digest: sha256:a30c906833977efbab3261de9950c1da8ecf464077c2137e7d1e17406c5af7f1
    tag: 1.9.1
    enabled: true
  enUSEmilyV3Voice:
    catalogName: en-US_EmilyV3Voice
    repository: watson-tts-en-us-emilyv3voice
    digest: sha256:1dd0f1e5b22f730bcc1bc3382f4a1c80a5f5ba2a8afb0029a1d46656f6eeb438
    tag: 1.9.1
    enabled: false
  enUSEmmaExpressive:
    catalogName: en-US_EmmaExpressive
    repository: watson-tts-en-us-emmaexpressive
    digest: sha256:c1012e46c4b6b3d12d0ee5425118286e59ca462f24e7472cea8026a462aeaae2
    tag: 1.9.1
    enabled: false
  enUSHenryV3Voice:
    catalogName: en-US_HenryV3Voice
    repository: watson-tts-en-us-henryv3voice
    digest: sha256:339076f6e5fd7d62d3e07602918772c4508ed2466bc354a23a09df8650b010be
    tag: 1.9.1
    enabled: false
  enUSKevinV3Voice:
    catalogName: en-US_KevinV3Voice
    repository: watson-tts-en-us-kevinv3voice
    digest: sha256:79d69ca2a4fb691bea69cd70c0038f36392a163e8b1febc82c1b44b0faf6800e
    tag: 1.9.1
    enabled: false
  enUSLisaExpressive:
    catalogName: en-US_LisaExpressive
    repository: watson-tts-en-us-lisaexpressive
    digest: sha256:07997289578be15125349f6eb09c91f4f67affedf1fd27f5aa8f8be8bdd76f4c
    tag: 1.9.1
    enabled: false
  enUSLisaV3Voice:
    catalogName: en-US_LisaV3Voice
    repository: watson-tts-en-us-lisav3voice
    digest: sha256:a39650058e23a50d0fbff4ea0cf9dd9fa89dc2a4fa9028dda4a8df00b31e5576
    tag: 1.9.1
    enabled: false
  enUSMichaelExpressive:
    catalogName: en-US_MichaelExpressive
    repository: watson-tts-en-us-michaelexpressive
    digest: sha256:78dbdc9a9cd15d0ff01ad7d3f2c79ef4121587f7f9aa341a1a2fa5a35a566c14
    tag: 1.9.1
    enabled: false
  enUSMichaelV3Voice:
    catalogName: en-US_MichaelV3Voice
    repository: watson-tts-en-us-michaelv3voice
    digest: sha256:9ac89d35c41ce660cd68007f3408f0a3d6e2527063399dad93e95d6dcf91676c
    tag: 1.9.1
    enabled: true
  enUSOliviaV3Voice:
    catalogName: en-US_OliviaV3Voice
    repository: watson-tts-en-us-oliviav3voice
    digest: sha256:96bccf2a0e59e86b6619412020f51e9a8b4b0f53f415498bd4bb47bed229414a
    tag: 1.9.1
    enabled: false
  esESEnriqueV3Voice:
    catalogName: es-ES_EnriqueV3Voice
    repository: watson-tts-es-es-enriquev3voice
    digest: sha256:46eb1521eb2cf659b8a674198b7c0bd2d60fa6a0e683b6f38ef317d7da963fa8
    tag: 1.9.1
    enabled: false
  esESLauraV3Voice:
    catalogName: es-ES_LauraV3Voice
    repository: watson-tts-es-es-laurav3voice
    digest: sha256:10861e589004b1d2edba99e6dfacb83dc7251af5dadefefae7ed8b4495bd611d
    tag: 1.9.1
    enabled: false
  esLASofiaV3Voice:
    catalogName: es-LA_SofiaV3Voice
    repository: watson-tts-es-la-sofiav3voice
    digest: sha256:d72bf91ca1aea8ef6378eefb66eb72cb6b6cfd6ab6fb8a7280f52cb3e6e6fc0c
    tag: 1.9.1
    enabled: false
  esUSSofiaV3Voice:
    catalogName: es-US_SofiaV3Voice
    repository: watson-tts-es-us-sofiav3voice
    digest: sha256:cd338d34463a77ff083f7391abeffb6b0eb22a95042c69b676808e63bdf5a30d
    tag: 1.9.1
    enabled: false
  frCALouiseV3Voice:
    catalogName: fr-CA_LouiseV3Voice
    repository: watson-tts-fr-ca-louisev3voice
    digest: sha256:6c36865d41b24a40f7e4aa08e57875a34ecdb1002d6c16551b1d2d1464e806f5
    tag: 1.9.1
    enabled: false
  frFRNicolasV3Voice:
    catalogName: fr-FR_NicolasV3Voice
    repository: watson-tts-fr-fr-nicolasv3voice
    digest: sha256:c5a39732043d3296cc9203cc9cd1cdff6846aa0b948da78f8d0636aedb229b76
    tag: 1.9.1
    enabled: false
  frFRReneeV3Voice:
    catalogName: fr-FR_ReneeV3Voice
    repository: watson-tts-fr-fr-reneev3voice
    digest: sha256:0f3b5f5b55a8835943f72a40f421901ae54a2e7b6dfbb8ecdc6af1ce87417f33
    tag: 1.9.1
    enabled: false
  itITFrancescaV3Voice:
    catalogName: it-IT_FrancescaV3Voice
    repository: watson-tts-it-it-francescav3voice
    digest: sha256:36fde461af1d30e656c8c5af6d73f384c7841b28e6581e9a6fc561b0a11c989a
    tag: 1.9.1
    enabled: false
  jaJPEmiV3Voice:
    catalogName: ja-JP_EmiV3Voice
    repository: watson-tts-ja-jp-emiv3voice
    digest: sha256:eefd736707c05fc2485e4711f6b41d01d182e9aa7cef8b60f81d523bef9236ac
    tag: 1.9.1
    enabled: false
  koKRJinV3Voice:
    catalogName: ko-KR_JinV3Voice
    repository: watson-tts-ko-kr-jinv3voice
    digest: sha256:d0057d82b3c3dda89273a8f80dcee7e3f252fbeb6772f47e8c977529117bdda9
    tag: 1.9.1
    enabled: false
  nlNLMerelV3Voice:
    catalogName: nl-NL_MerelV3Voice
    repository: watson-tts-nl-nl-merelv3voice
    digest: sha256:edc86d00faeebc75d74e1ba48f76d14d1f57ce46a36c9b0fb0bdc3e16ff27089
    tag: 1.9.1
    enabled: false
  ptBRIsabelaV3Voice:
    catalogName: pt-BR_IsabelaV3Voice
    repository: watson-tts-pt-br-isabelav3voice
    digest: sha256:3095303a2007bff0d91003f6f13b3f412effd19ed631f1fac637b2fb172e8899
    tag: 1.9.1
    enabled: false
